import { createClient } from "npm:@supabase/supabase-js@2";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
const MAX_BODY_BYTES=512*1024;const ASAAS_SANDBOX_URL="https://api-sandbox.asaas.com/v3";const ASAAS_PRODUCTION_URL="https://api.asaas.com/v3";
const cors=(req:Request)=>{const origin=req.headers.get("origin");let allowed="null";try{if(origin){const{hostname,protocol}=new URL(origin);const suffixes=[".lovable.app",".lovableproject.com",".lovable.dev"];const extra=(Deno.env.get("ALLOWED_ORIGINS")??"").split(",").map(s=>s.trim()).filter(Boolean);if(hostname==="localhost"||hostname==="127.0.0.1"||extra.includes(origin)||(protocol==="https:"&&suffixes.some(s=>hostname.endsWith(s))))allowed=origin}}catch{}return{"Access-Control-Allow-Origin":allowed,"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, asaas-access-token","Access-Control-Allow-Methods":"GET, POST, OPTIONS","Vary":"Origin"}};
const json=(h:Record<string,string>,b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...h,"Content-Type":"application/json"}});
const readBody=async(req:Request)=>{const n=Number(req.headers.get("content-length")??0);if(n>MAX_BODY_BYTES)throw new Error("payload_too_large");const t=await req.text();if(t.length>MAX_BODY_BYTES)throw new Error("payload_too_large");return t?JSON.parse(t):{}};
async function requireUser(req:Request){const auth=req.headers.get("Authorization")??"";const token=auth.startsWith("Bearer ")?auth.slice(7).trim():"";const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!token||!url||!key)return null;const admin=createClient(url,key,{auth:{persistSession:false}});const{data}=await admin.auth.getUser(token);return data?.user??null}
const base=()=>((Deno.env.get("ASAAS_ENVIRONMENT")??"sandbox").toLowerCase()==="production"?ASAAS_PRODUCTION_URL:ASAAS_SANDBOX_URL);const apiKey=()=>Deno.env.get("ASAAS_API_KEY")?.trim()??"";
async function asaasJson(path:string,init:RequestInit={}){const key=apiKey();if(!key)throw Object.assign(new Error("asaas_not_configured"),{status:503});const headers=new Headers(init.headers);headers.set("Content-Type","application/json");headers.set("Accept","application/json");headers.set("User-Agent","MARCENAPP/1.0 (billing)");headers.set("access_token",key);const r=await fetch(`${base()}${path}`,{...init,headers});const b=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error("asaas_upstream_error"),{status:r.status,body:b});return b}
async function admin(){const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!key)throw Object.assign(new Error("server_config_incomplete"),{status:500});return createClient(url,key,{auth:{persistSession:false}})}
const products={image_single:{name:"Imagem profissional avulsa",creditType:"image",credits:1,amount:50},image_pack_5:{name:"Pacote MARCENA — 5 imagens",creditType:"image",credits:5,amount:199},contract_single:{name:"Contrato avulso",creditType:"contract",credits:1,amount:29.9},contract_pack_5:{name:"Pacote de contratos — 5",creditType:"contract",credits:5,amount:99},cut_plan_single:{name:"Plano de corte avulso",creditType:"cut_plan",credits:1,amount:39.9},marcena_essencial:{name:"MARCENA Essencial",creditType:"marcena",credits:1,amount:29.9},marcena_profissional:{name:"MARCENA Profissional",creditType:"marcena",credits:3,amount:79.9}} as const;
serve(async req=>{const h=cors(req);if(req.method==="OPTIONS")return new Response(null,{headers:h});try{const body=await readBody(req);const action=String(body.action??"");
if(action==="webhook"){if(req.method!=="POST")return json(h,{error:"Method not allowed"},405);const expected=Deno.env.get("ASAAS_WEBHOOK_TOKEN")?.trim(),received=req.headers.get("asaas-access-token")?.trim();if(!expected||!received||expected!==received)return json(h,{error:"Webhook não autorizado."},401);const event=body.event;if(!event?.id||!event?.event)return json(h,{error:"Evento Asaas inválido."},400);const a=await admin();const payment=event.payment??{};const subscriptionId=payment.subscription??event.subscription?.id??null;const{error}=await a.from("asaas_webhook_events").insert({event_id:event.id,event_type:event.event,payment_id:payment.id??null,customer_id:payment.customer??event.customer?.id??null,subscription_id:subscriptionId,payload:event});if(error&&!String(error.message).toLowerCase().includes("duplicate"))return json(h,{error:"Não foi possível registrar o webhook."},500);if(event.subscription?.id&&event.subscription?.status)await a.from("billing_subscriptions").update({status:String(event.subscription.status),updated_at:new Date().toISOString()}).eq("asaas_subscription_id",String(event.subscription.id));if(payment.id){const status=String(payment.status??event.event??"PENDING");const receivedStatus=["RECEIVED","CONFIRMED","RECEIVED_IN_CASH"].includes(status)||event.event==="PAYMENT_RECEIVED";const{data:purchase}=await a.from("billing_purchases").select("id,user_id,credit_type,credits,status").eq("asaas_payment_id",String(payment.id)).maybeSingle();if(purchase){await a.from("billing_purchases").update({status,updated_at:new Date().toISOString()}).eq("id",purchase.id);if(receivedStatus&&purchase.status!=="RECEIVED")await a.rpc("grant_billing_credits",{p_user_id:purchase.user_id,p_credit_type:purchase.credit_type,p_credits:purchase.credits})}}return json(h,{received:true,duplicate:Boolean(error)})}
const user=await requireUser(req);if(!user)return json(h,{error:"Autenticação necessária."},401);
if(action==="connection_status"){const key=apiKey();if(!key)return json(h,{connected:false,configured:false,environment:Deno.env.get("ASAAS_ENVIRONMENT")??"sandbox"});const r=await asaasJson("/customers?limit=1");return json(h,{connected:true,configured:true,environment:Deno.env.get("ASAAS_ENVIRONMENT")??"sandbox",customerCount:Number(r.totalCount??0)})}
if(action==="list_customers"){const p=new URLSearchParams({limit:String(Math.min(Number(body.limit??20),100)),offset:String(Math.max(Number(body.offset??0),0))});for(const k of ["externalReference","cpfCnpj","email"])if(body[k])p.set(k,String(body[k]));return json(h,await asaasJson(`/customers?${p}`))}
if(action==="create_customer"){const customer={name:String(body.name??"").trim(),cpfCnpj:body.cpfCnpj?String(body.cpfCnpj).replace(/\D/g,""):undefined,email:body.email?String(body.email).trim():undefined,mobilePhone:body.mobilePhone?String(body.mobilePhone).replace(/\D/g,""):undefined,externalReference:body.externalReference?String(body.externalReference):undefined};if(!customer.name)return json(h,{error:"Nome do cliente é obrigatório."},400);const existing=customer.externalReference?await asaasJson(`/customers?externalReference=${encodeURIComponent(customer.externalReference)}&limit=1`):null;if(existing?.data?.[0])return json(h,{customer:existing.data[0],reused:true});return json(h,{customer:await asaasJson("/customers",{method:"POST",body:JSON.stringify(customer)}),reused:false})}
if(action==="create_payment"){const customer=String(body.customerId??"").trim(),value=Number(body.value),billingType=String(body.billingType??"UNDEFINED");if(!customer||!Number.isFinite(value)||value<=0)return json(h,{error:"Cliente e valor válido são obrigatórios."},400);if(!["UNDEFINED","BOLETO","PIX","CREDIT_CARD"].includes(billingType))return json(h,{error:"Forma de pagamento inválida."},400);return json(h,{payment:await asaasJson("/payments",{method:"POST",body:JSON.stringify({customer,billingType,value,dueDate:body.dueDate??new Date().toISOString().slice(0,10),description:body.description?String(body.description).slice(0,500):undefined,externalReference:body.externalReference?String(body.externalReference):undefined,installmentCount:body.installmentCount?Number(body.installmentCount):undefined,totalValue:body.totalValue?Number(body.totalValue):undefined})})})}
if(action==="create_product_payment"){const product=products[String(body.productKey??"") as keyof typeof products];if(!product)return json(h,{error:"Produto avulso inválido."},400);const customer=String(body.customerId??"").trim();if(!customer)return json(h,{error:"Cliente Asaas obrigatório."},400);const billingType=String(body.billingType??"UNDEFINED");if(!["UNDEFINED","BOLETO","PIX","CREDIT_CARD"].includes(billingType))return json(h,{error:"Forma de pagamento inválida."},400);const a=await admin(),externalReference=`marcenapp:product:${body.productKey}:${user.id}:${crypto.randomUUID()}`,payment=await asaasJson("/payments",{method:"POST",body:JSON.stringify({customer,billingType,value:product.amount,dueDate:body.dueDate??new Date().toISOString().slice(0,10),description:product.name,externalReference})});const{error}=await a.from("billing_purchases").insert({user_id:user.id,product_key:String(body.productKey),product_name:product.name,credit_type:product.creditType,credits:product.credits,amount:product.amount,asaas_customer_id:customer,asaas_payment_id:String(payment.id),status:String(payment.status??"PENDING")});if(error)return json(h,{error:"Cobrança criada, mas não foi possível registrar a compra no MARCENAPP."},502);return json(h,{payment,product})}
if(action==="get_wallet"){const a=await admin(),{data,error}=await a.from("billing_wallets").select("image_credits,contract_credits,cut_plan_credits,marcena_credits,updated_at").eq("user_id",user.id).maybeSingle();if(error)return json(h,{error:"Não foi possível carregar seus créditos."},500);return json(h,{wallet:data??{image_credits:0,contract_credits:0,cut_plan_credits:0,marcena_credits:0}})}
if(action==="create_subscription"){const customer=String(body.customerId??"").trim(),value=Number(body.value),billingType=String(body.billingType??"UNDEFINED"),cycle=String(body.cycle??"MONTHLY"),plan=String(body.plan??"").toLowerCase();if(!customer||!Number.isFinite(value)||value<=0)return json(h,{error:"Cliente e valor válido são obrigatórios."},400);if(!["UNDEFINED","BOLETO","CREDIT_CARD","PIX"].includes(billingType))return json(h,{error:"Forma de pagamento inválida."},400);if(!["start","pro","business"].includes(plan))return json(h,{error:"Plano MARCENAPP inválido."},400);const nextDueDate=String(body.nextDueDate??new Date().toISOString().slice(0,10)),subscription=await asaasJson("/subscriptions",{method:"POST",body:JSON.stringify({customer,billingType,value,cycle,nextDueDate,description:body.description?String(body.description).slice(0,500):undefined,externalReference:body.externalReference?String(body.externalReference):`marcenapp:${user.id}:${plan}`})}),a=await admin(),{error}=await a.from("billing_subscriptions").insert({user_id:user.id,plan,asaas_customer_id:customer,asaas_subscription_id:String(subscription.id),status:String(subscription.status??"ACTIVE"),trial_ends_at:nextDueDate});if(error)return json(h,{error:"Assinatura criada no Asaas, mas não foi possível registrar no MARCENAPP."},502);return json(h,{subscription})}
if(action==="get_payment"){const paymentId=String(body.paymentId??"").trim();if(!paymentId)return json(h,{error:"paymentId é obrigatório."},400);return json(h,{payment:await asaasJson(`/payments/${encodeURIComponent(paymentId)}`)})}
if(action==="get_pix_qr"){const paymentId=String(body.paymentId??"").trim();if(!paymentId)return json(h,{error:"paymentId é obrigatório."},400);return json(h,{pix:await asaasJson(`/payments/${encodeURIComponent(paymentId)}/pixQrCode`)})}
return json(h,{error:"Ação Asaas desconhecida."},400)
}catch(error){console.error("asaas error",error);const status=Number((error as Error&{status?:number}).status??500);if((error as Error).message==="asaas_not_configured")return json(h,{error:"Asaas não está configurado no servidor."},503);if((error as Error).message==="payload_too_large")return json(h,{error:"Corpo da requisição muito grande."},413);if(status===401||status===403)return json(h,{error:"Asaas recusou a credencial ou a operação."},502);return json(h,{error:"Falha ao processar integração Asaas."},status>=400&&status<600?status:500)}});