export type IaraExecutionStatus = 'idle' | 'understanding' | 'planning' | 'executing' | 'waiting' | 'completed' | 'failed' | 'cancelled';
export type IaraExecutionError = { code?: string; message: string; retryable?: boolean };
export type IaraExecutionArtifact = { type: string; id?: string; url?: string; mimeType?: string };
export type IaraExecution = { id:string; correlationId:string; userId:string; projectId:string|null; environmentId:string|null; versionId:string|null; intent:string|null; action:string|null; agent:string|null; status:IaraExecutionStatus; progress:number; startedAt:string|null; updatedAt:string; completedAt:string|null; error:IaraExecutionError|null; artifacts:IaraExecutionArtifact[]; result:Record<string,unknown>|null };
export type IaraExecutionPatch = Partial<Omit<IaraExecution,'id'|'correlationId'|'userId'>> & { status?: IaraExecutionStatus };
const TRANSITIONS: Record<IaraExecutionStatus, readonly IaraExecutionStatus[]> = { idle:['understanding','cancelled'], understanding:['planning','executing','waiting','failed','cancelled'], planning:['executing','waiting','failed','cancelled'], executing:['executing','waiting','completed','failed','cancelled'], waiting:['executing','completed','failed','cancelled'], completed:[], failed:['understanding'], cancelled:['understanding'] };
export function canTransition(from:IaraExecutionStatus,to:IaraExecutionStatus){ return from===to || TRANSITIONS[from].includes(to); }
export function createIaraExecution(input:{id:string;correlationId:string;userId:string;projectId?:string|null;environmentId?:string|null;versionId?:string|null;intent?:string|null;action?:string|null;agent?:string|null;now?:string}):IaraExecution { const now=input.now??new Date().toISOString(); return {id:input.id,correlationId:input.correlationId,userId:input.userId,projectId:input.projectId??null,environmentId:input.environmentId??null,versionId:input.versionId??null,intent:input.intent??null,action:input.action??null,agent:input.agent??null,status:'understanding',progress:15,startedAt:now,updatedAt:now,completedAt:null,error:null,artifacts:[],result:null}; }
export function transitionIaraExecution(execution:IaraExecution,status:IaraExecutionStatus,patch:IaraExecutionPatch={},now=new Date().toISOString()):IaraExecution { if(!canTransition(execution.status,status)) throw new Error('Transição de execução inválida: '+execution.status+' → '+status); const defaults:Record<IaraExecutionStatus,number>={idle:0,understanding:15,planning:30,executing:60,waiting:75,completed:100,failed:execution.progress,cancelled:execution.progress}; const terminal=status==='completed'||status==='failed'||status==='cancelled'; return {...execution,...patch,status,progress:patch.progress??defaults[status],updatedAt:now,completedAt:terminal?(patch.completedAt??now):null}; }
export function appendIaraExecutionArtifact(execution:IaraExecution,artifact:IaraExecutionArtifact,now=new Date().toISOString()):IaraExecution { return {...execution,artifacts:[...execution.artifacts,artifact],updatedAt:now}; }