import type {IntentResolver,IntentResolverInput,ResolvedIntent,SlotRequirement} from "./types";
const WORDS:Array<[RegExp,string]>=[[/\\bduas?\\b/g,"2"],[/\\btrês\\b/g,"3"],[/\\btres\\b/g,"3"],[/\\bquatro\\b/g,"4"],[/\\bcinco\\b/g,"5"],[/\\bseis\\b/g,"6"],[/\\bsete\\b/g,"7"],[/\\boito\\b/g,"8"],[/\\bnove\\b/g,"9"],[/\\bdez\\b/g,"10"]];
const norm=(s:string)=>s.toLocaleLowerCase("pt-BR").replace(/\\s+/g," ").trim();
const words=(s:string)=>WORDS.reduce((v,[r,n])=>v.replace(r,n),s);
function mm(v:string,u?:string){const n=Number(v.replace(",","."));if(!Number.isFinite(n)||n<=0)return undefined;const x=(u??"mm").toLowerCase();return x.startsWith("m")&&!x.startsWith("mm")?n*1000:x.startsWith("cm")?n*10:n;}
const triple=/(\\d+(?:[.,]\\d+)?)\\s*(mm|cm|m|metros?|centímetros?)?\\s*[x×]\\s*(\\d+(?:[.,]\\d+)?)\\s*(mm|cm|m|metros?|centímetros?)?\\s*[x×]\\s*(\\d+(?:[.,]\\d+)?)\\s*(mm|cm|m|metros?|centímetros?)?/i;
function dims(s:string){const m=s.match(triple);if(!m)return;const a=mm(m[1],m[2]),b=mm(m[3],m[4]),c=mm(m[5],m[6]);return a&&b&&c?{width:a,height:b,depth:c}:undefined}
function axis(s:string,a:"width"|"height"|"depth"){const w=a==="width"?"(?:largura|largo|comprimento)":a==="height"?"(?:altura|alto)":"(?:profundidade|profundo)";const m=s.match(new RegExp(w+"\\s*(?:é|e|de|:|=)?\\s*(\\d+(?:[.,]\\d+)?)\\s*(mm|cm|m|metros?|centímetros?)?","i"));return m?mm(m[1],m[2]):undefined}
function extract(s:string){const d=dims(s);if(d)return d;const width=axis(s,"width"),height=axis(s,"height"),depth=axis(s,"depth");return width&&height&&depth?{width,height,depth}:undefined}
const create=/\\b(crie|criar|cria|quero|preciso|gostaria|novo projeto|novo móvel|novo movel|monte um projeto|faça um projeto|faca um projeto)\\b/i;
const noun=/\\b(projeto|móvel|movel|armário|armario|cozinha|bancada)\\b/i;
const render=/\\b(gera|gerar|crie|criar|quero ver|visualiza|visualizar|mostra|mostrar|renderize|renderizar)\\b.*\\b(render|imagem|visualização|visualizacao)\\b/i;
const actions:Record<string,string[]>={cut:["corte","chapa"],materials:["material","materiais","mdf"],hardware:["ferragem","ferragens"],inventory:["estoque"],production:["produção","producao","fabricar"],budget:["orçamento","orcamento","preço","preco","custo"],documents:["documento","documentos","contrato"],order:["pedido"],assembly:["montagem","montar"],installation:["instalação","instalacao","instalar"],checklist:["checklist"],delivery:["entrega"],review_project:["revisar projeto","conferir projeto"],check_measurements:["conferir medida","conferir medidas"]};
function createProject(s:string):ResolvedIntent|null{if(!create.test(s)||!noun.test(s))return null;const d=extract(s);const missing:SlotRequirement[]=d?[]:[{tool:"createProjeto",field:"width",label:"Qual a largura do móvel?"},{tool:"createProjeto",field:"height",label:"Qual a altura do móvel?"},{tool:"createProjeto",field:"depth",label:"Qual a profundidade do móvel?"}];return{intent:"create_projeto",entities:{nome:"Novo projeto",...(d??{})},confidence:d?.width&&d.height&&d.depth?0.95:0.6,missingSlots:missing,source:"deterministic"} as ResolvedIntent}
export const deterministicResolver:IntentResolver={name:"deterministic",async resolve(input){if(input.images?.length)return null;const s=words(norm(input.text));const p=createProject(s);if(p)return p;if(render.test(s))return{intent:"gerar_render",entities:{prompt:input.text},confidence:.9,missingSlots:[],source:"deterministic"};for(const [action,ks] of Object.entries(actions))if(ks.some(k=>s.includes(k)))return{intent:"smart_action",entities:{action},confidence:.85,missingSlots:[],source:"deterministic"};return null;}};
