import { ArrowRight, Check, ChevronDown, ClipboardList, Cuboid, FileText, Hammer, Layers3, Menu, Ruler, Scissors, X } from 'lucide-react';
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import logo from '@/assets/marcenapp-logo.svg';

const resources = [
  { icon: ClipboardList, title: 'Projeto', headline: 'Organize cada projeto em um único ambiente.', text: 'Tenha as informações do projeto reunidas e estruturadas.' },
  { icon: Layers3, title: 'Ambiente', headline: 'Estruture o ambiente antes de desenvolver o móvel.', text: 'Organize o espaço e as informações necessárias para o projeto.' },
  { icon: Ruler, title: 'Dimensionamento', headline: 'Trabalhe com as medidas do móvel de forma organizada.', text: 'Transforme as dimensões do projeto em informações úteis para as próximas etapas.' },
  { icon: Cuboid, title: '2D e 3D', headline: 'Veja o projeto antes de produzir.', text: 'Confira o desenvolvimento do móvel e entenda o resultado antes de avançar.' },
  { icon: Layers3, title: 'Materiais', headline: 'Organize os materiais usados no projeto.', text: 'Mantenha as informações de materiais associadas ao projeto.' },
  { icon: Hammer, title: 'Ferragens', headline: 'Mantenha as ferragens associadas ao projeto.', text: 'Organize os componentes necessários para a execução do móvel.' },
  { icon: Scissors, title: 'Lista de corte', headline: 'Transforme o projeto em informação para produção.', text: 'Reúna as informações necessárias para preparar o corte das peças.' },
  { icon: FileText, title: 'Orçamento', headline: 'Leve as informações do projeto para o orçamento.', text: 'Use os dados do projeto como base para organizar o orçamento.' },
];
const flow = [['01','Projeto','Comece o projeto e organize o ambiente que será desenvolvido.'],['02','Desenvolver','Trabalhe com medidas, módulos e detalhes do móvel.'],['03','Visualizar','Confira o projeto em 2D e 3D antes de produzir.'],['04','Configurar','Organize materiais, ferragens e demais informações.'],['05','Preparar','Reúna as informações para corte, orçamento e produção.']];
const faqs = [['O que é o Marcenapp?','O Marcenapp é uma plataforma para profissionais de marcenaria que reúne projeto, dimensionamento, visualização, materiais, ferragens, lista de corte e orçamento em um único fluxo de trabalho.'],['Para quem ele foi desenvolvido?','Para quem trabalha com móveis sob medida: marceneiros, marcenarias, projetistas e profissionais de móveis planejados.'],['Preciso saber trabalhar em 3D?','O Marcenapp foi pensado para acompanhar o desenvolvimento do projeto e permitir a visualização em 2D e 3D antes da produção.'],['Como funciona a inteligência artificial?','A Yara ajuda a interpretar informações e acompanhar etapas do projeto dentro do fluxo de trabalho. Você continua no controle.'],['O Marcenapp gera lista de corte?','O sistema reúne as informações do projeto necessárias para preparar a etapa de corte, conforme os recursos disponíveis no projeto.'],['Como funcionam os créditos?','Os detalhes de créditos e condições devem ser consultados na configuração comercial atual da plataforma.']];

const Landing = () => {
  const navigate = useNavigate(); const [menuOpen,setMenuOpen]=useState(false); const [openFaq,setOpenFaq]=useState<number|null>(null); const goAuth=()=>navigate('/auth');
  return <div className="min-h-screen overflow-x-hidden bg-background text-foreground">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-border/80 bg-background/95 backdrop-blur"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8">
      <button onClick={()=>window.scrollTo({top:0,behavior:'smooth'})} className="flex items-center gap-3"><img src={logo} alt="Marcenapp" className="h-10 w-10 rounded-xl"/><div className="text-left leading-tight"><div className="text-lg font-black tracking-tight">MARCENAPP</div><div className="text-[10px] font-bold uppercase tracking-[0.18em] text-muted-foreground">Marcenaria</div></div></button>
      <nav className="hidden items-center gap-7 md:flex"><a href="#recursos" className="text-sm font-semibold text-muted-foreground hover:text-primary">Recursos</a><a href="#fluxo" className="text-sm font-semibold text-muted-foreground hover:text-primary">Como funciona</a><a href="#yara" className="text-sm font-semibold text-muted-foreground hover:text-primary">Yara</a><a href="#planos" className="text-sm font-semibold text-muted-foreground hover:text-primary">Planos</a><button onClick={goAuth} className="rounded-xl px-4 py-2 text-sm font-bold text-foreground hover:bg-primary/10">Entrar</button><button onClick={goAuth} className="rounded-xl bg-primary px-5 py-2.5 text-sm font-black text-primary-foreground shadow-sm hover:bg-primary/90">Começar agora</button></nav>
      <button className="rounded-xl p-2 md:hidden" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Abrir menu">{menuOpen?<X/>:<Menu/>}</button></div>
      {menuOpen&&<div className="border-t border-border bg-background px-5 py-5 md:hidden"><div className="flex flex-col gap-2">{['#recursos','#fluxo','#yara','#planos'].map(h=><a key={h} href={h} onClick={()=>setMenuOpen(false)} className="rounded-xl px-3 py-3 font-semibold text-muted-foreground hover:bg-primary/10 hover:text-primary">{h==='#recursos'?'Recursos':h==='#fluxo'?'Como funciona':h==='#yara'?'Yara':'Planos'}</a>)}<button onClick={goAuth} className="mt-2 rounded-xl bg-primary px-4 py-3 font-black text-primary-foreground">Entrar ou começar</button></div></div>}
    </header>
    <main>
      <section className="px-5 pb-16 pt-32 lg:px-8 lg:pb-24 lg:pt-40"><div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[.92fr_1.08fr]"><div>
        <p className="mb-5 text-sm font-black uppercase tracking-[0.18em] text-primary">Feito para quem projeta e produz móveis sob medida</p><h1 className="max-w-3xl text-5xl font-black leading-[0.98] tracking-[-0.04em] sm:text-6xl lg:text-7xl">Do projeto à produção, <span className="text-primary">tudo no lugar.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-muted-foreground sm:text-xl">Desenvolva seus projetos de marcenaria, visualize em 2D e 3D e organize medidas, materiais, ferragens, lista de corte e orçamento em um único fluxo de trabalho.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><button onClick={goAuth} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-primary px-7 py-4 font-black text-primary-foreground shadow-sm hover:bg-primary/90">Começar agora <ArrowRight size={18}/></button><a href="#historia" className="inline-flex items-center justify-center rounded-2xl border border-primary/20 bg-card px-7 py-4 font-bold text-foreground hover:bg-primary/5">Conhecer o Marcenapp</a></div><p className="mt-5 text-sm font-medium text-muted-foreground">Tecnologia no produto. Naturalidade na comunicação.</p>
      </div><div id="historia" className="relative rounded-[2rem] border border-primary/15 bg-card p-4 shadow-sm sm:p-5"><div className="mb-4 flex items-center justify-between px-1"><div><div className="text-xs font-black uppercase tracking-[0.16em] text-primary/70">O trabalho real</div><div className="mt-1 text-xl font-black">Do cliente ao projeto</div></div><div className="rounded-full border border-primary/20 bg-primary/5 px-3 py-1 text-[11px] font-bold text-primary">01 — 03</div></div>
        <div className="grid gap-3 sm:grid-cols-3"><div className="relative min-h-[250px] overflow-hidden rounded-2xl bg-primary/10 p-4"><div className="absolute inset-0 bg-[linear-gradient(135deg,#eef2ff_0%,#dbeafe_55%,#bfdbfe_100%)]"/><div className="absolute bottom-0 left-0 right-0 h-24 bg-primary/10"/><div className="absolute bottom-8 left-7 h-32 w-20 rounded-t-[2rem] bg-primary/70"/><div className="absolute bottom-24 left-20 h-28 w-12 rotate-[-12deg] rounded-xl bg-indigo-500"/><div className="absolute right-7 top-10 h-20 w-16 rounded-lg border-4 border-primary bg-white shadow-lg"/><div className="absolute bottom-4 left-4 rounded-lg bg-white/95 px-2.5 py-1.5 text-[10px] font-black text-primary">CASA DO CLIENTE</div><div className="absolute right-4 top-4 rounded-full bg-white/95 px-2.5 py-1 text-[10px] font-bold text-primary">Foto</div></div>
        <div className="relative min-h-[250px] overflow-hidden rounded-2xl bg-slate-950 p-3"><div className="absolute inset-x-4 top-4 h-4 rounded-full bg-indigo-900"/><div className="absolute inset-x-4 top-12 bottom-10 rounded-xl border border-primary/20 bg-slate-900 p-3"><div className="h-3 w-20 rounded bg-primary/70"/><div className="mt-4 grid grid-cols-[1.1fr_.9fr] gap-2"><div className="rounded-lg border border-primary/20 bg-indigo-950 p-2"><div className="mt-5 h-20 rounded bg-primary/30"/><div className="mt-2 h-2 w-16 rounded bg-amber-400"/></div><div className="space-y-2"><div className="h-7 rounded bg-indigo-900"/><div className="h-7 rounded bg-indigo-900"/><div className="h-7 rounded bg-indigo-900"/></div></div></div><div className="absolute bottom-3 left-3 text-[10px] font-black tracking-wide text-blue-200">PROJETO NO MARCENAPP</div></div>
        <div className="relative min-h-[250px] overflow-hidden rounded-2xl bg-primary/5 p-3"><div className="absolute inset-0 bg-[linear-gradient(135deg,#f8fafc_0%,#eef2ff_50%,#dbeafe_100%)]"/><div className="absolute bottom-10 left-5 right-5 h-28 rounded-t-xl border border-primary/25 bg-white shadow-sm"/><div className="absolute bottom-10 left-5 top-28 w-8 bg-primary/20"/><div className="absolute bottom-10 right-5 top-28 w-8 bg-primary/20"/><div className="absolute bottom-24 left-12 right-12 h-16 rounded border border-primary/20 bg-white"/><div className="absolute left-4 top-4 rounded-full bg-white/95 px-2.5 py-1 text-[10px] font-bold text-primary">Resultado</div><div className="absolute bottom-4 right-4 rounded-lg bg-primary px-2.5 py-1.5 text-[10px] font-black text-white">PRONTO</div></div></div><div className="mt-4 grid grid-cols-3 gap-3 text-[11px] font-bold text-muted-foreground"><div>01 · Entender</div><div>02 · Desenvolver</div><div>03 · Produzir</div></div></div></div></section>

      <section className="border-y border-border bg-card px-5 py-16 lg:px-8 lg:py-20"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-sm font-black uppercase tracking-[0.18em] text-primary">O problema</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">Um projeto de marcenaria não termina no desenho.</h2><p className="mt-5 text-lg leading-8 text-muted-foreground">Depois do desenho vêm as medidas, materiais, espessuras, ferragens, detalhes construtivos, lista de corte e orçamento.</p><p className="mt-4 text-lg font-bold leading-8">Quando essas informações ficam espalhadas, acompanhar o projeto fica mais difícil e aumenta a chance de retrabalho.</p></div><div className="mt-10 flex flex-wrap items-center gap-2 text-sm font-bold text-muted-foreground sm:gap-3">{['Projeto','Medidas','Materiais','Ferragens','Corte','Orçamento','Produção'].map((x,i)=><div key={x} className="flex items-center gap-2"><span className="rounded-full border border-primary/15 bg-primary/5 px-3 py-2 text-primary">{x}</span>{i<6&&<ArrowRight size={14} className="text-primary/40"/>}</div>)}</div></div></section>

      <section className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="text-sm font-black uppercase tracking-[0.18em] text-primary">A solução</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">Uma ferramenta pensada para o trabalho real da marcenaria.</h2></div><div className="rounded-3xl border border-primary/15 bg-card p-7 shadow-sm sm:p-9"><p className="text-lg leading-8 text-muted-foreground">O Marcenapp reúne as principais informações do projeto em um único fluxo de trabalho, ajudando você a organizar o caminho entre o projeto e a produção.</p><p className="mt-5 text-xl font-black">Menos informação espalhada. <span className="text-primary">Mais controle</span> sobre o projeto.</p></div></div></section>

      <section id="fluxo" className="border-y border-primary/20 bg-slate-950 px-5 py-20 text-white lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-sm font-black uppercase tracking-[0.18em] text-blue-300">Como funciona</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">Um projeto. Um fluxo de trabalho.</h2><p className="mt-5 text-lg leading-8 text-slate-300">Desenvolva, visualize, configure e prepare as informações sem perder a continuidade do projeto.</p><button onClick={goAuth} className="mt-8 inline-flex items-center gap-2 rounded-2xl bg-primary px-6 py-4 font-black text-white hover:bg-primary/90">Começar agora <ArrowRight size={18}/></button></div><div className="space-y-3">{flow.map(([n,t,tx])=><div key={n} className="grid gap-4 rounded-2xl border border-primary/20 bg-primary/[0.08] p-5 sm:grid-cols-[48px_180px_1fr] sm:items-center"><div className="text-xs font-black text-amber-400">{n}</div><h3 className="font-black">{t}</h3><p className="text-sm leading-6 text-blue-100/70">{tx}</p></div>)}</div></div></section>

      <section id="recursos" className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-sm font-black uppercase tracking-[0.18em] text-primary">O que o produto faz</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">Tudo o que o projeto precisa, no mesmo lugar.</h2><p className="mt-5 text-lg leading-8 text-muted-foreground">Cada recurso existe para acompanhar uma etapa do trabalho, sem tirar o foco do projeto.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{resources.map(({icon:Icon,title,headline,text})=><article key={title} className="rounded-3xl border border-primary/15 bg-card p-6 shadow-sm hover:-translate-y-0.5 hover:border-primary/30 hover:shadow-md"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon size={21} strokeWidth={1.8}/></div><p className="mt-6 text-xs font-black uppercase tracking-[0.16em] text-primary/70">{title}</p><h3 className="mt-2 text-lg font-black leading-6">{headline}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></article>)}</div></div></section>

      <section className="border-y border-border bg-card px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-sm font-black uppercase tracking-[0.18em] text-primary">Produto na prática</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">O projeto continua no centro.</h2><p className="mt-5 text-lg leading-8 text-muted-foreground">A experiência deve responder uma pergunta simples: é isso que eu vou encontrar quando entrar no Marcenapp?</p></div><div className="mt-10 grid gap-4 lg:grid-cols-3">{['Projeto e ambiente','Medidas e visualização','Materiais, ferragens e orçamento'].map((title,i)=><div key={title} className="overflow-hidden rounded-3xl border border-primary/15 bg-background"><div className="h-52 bg-primary/5 p-5">{i===0?<div className="h-full rounded-2xl border border-primary/15 bg-card p-4 shadow-sm"><div className="flex gap-2"><span className="h-3 w-20 rounded bg-primary/20"/><span className="h-3 w-10 rounded bg-primary/10"/></div><div className="mt-5 grid h-32 grid-cols-[1fr_.6fr] gap-3"><div className="rounded-xl bg-primary/10"/><div className="space-y-2"><div className="h-8 rounded-lg bg-primary/5"/><div className="h-8 rounded-lg bg-primary/5"/><div className="h-8 rounded-lg bg-primary/5"/></div></div></div>:i===1?<div className="relative h-full rounded-2xl border border-primary/15 bg-card p-4 shadow-sm"><div className="absolute left-8 top-8 h-28 w-40 rotate-[-4deg] rounded-lg border-2 border-primary/30"/><div className="absolute left-16 top-16 h-24 w-36 rotate-[5deg] rounded-lg border-2 border-primary/50"/><div className="absolute bottom-5 right-5 rounded-lg bg-primary px-3 py-2 text-[10px] font-black text-white">2D / 3D</div></div>:<div className="h-full rounded-2xl border border-primary/15 bg-card p-4 shadow-sm"><div className="space-y-2">{['MDF','Ferragens','Lista de corte','Orçamento'].map(x=><div key={x} className="flex items-center justify-between rounded-lg bg-primary/5 px-3 py-2 text-xs font-bold"><span>{x}</span><span className="text-primary/60">organizado</span></div>)}</div></div>}</div><div className="p-5"><h3 className="font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Uma visão objetiva do que acompanha o projeto dentro do sistema.</p></div></div>)}</div></div></section>

      <section id="yara" className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><p className="text-sm font-black uppercase tracking-[0.18em] text-primary">Yara / IA</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">Inteligência artificial trabalhando junto com o seu projeto.</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-muted-foreground">A Yara é a assistente de inteligência artificial do Marcenapp. Ela ajuda a interpretar informações e acompanhar etapas do projeto dentro do fluxo de trabalho.</p><p className="mt-5 text-lg font-black">Você continua no controle. <span className="text-primary">A Yara ajuda no processo.</span></p></div><div className="rounded-3xl border border-primary/15 bg-card p-6 shadow-sm"><div className="flex items-center gap-3 border-b border-border pb-5"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-sm font-black text-primary">Y</div><div><div className="font-black">Yara</div><div className="text-xs text-muted-foreground">Assistente do Marcenapp</div></div></div><div className="mt-5 space-y-3"><div className="max-w-[85%] rounded-2xl bg-primary/5 p-4 text-sm leading-6 text-muted-foreground">Como posso ajudar com este projeto?</div><div className="ml-auto max-w-[85%] rounded-2xl bg-primary p-4 text-sm leading-6 text-white">Quero organizar as informações do ambiente antes de seguir para a próxima etapa.</div><div className="max-w-[85%] rounded-2xl bg-primary/5 p-4 text-sm leading-6 text-muted-foreground">Vamos organizar isso dentro do fluxo do projeto.</div></div></div></div></section>

      <section className="border-y border-border bg-card px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="text-sm font-black uppercase tracking-[0.18em] text-primary">Diferencial</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">Mais do que projetar. Organize o caminho até a produção.</h2></div><div><div className="flex flex-wrap items-center gap-2 text-sm font-black">{['Projeto','Dimensionamento','Visualização','Materiais','Ferragens','Lista de corte','Orçamento'].map((x,i)=><div key={x} className="flex items-center gap-2"><span className="rounded-xl border border-primary/15 bg-primary/5 px-3 py-2.5 text-primary">{x}</span>{i<6&&<ArrowRight size={14} className="text-primary/40"/>}</div>)}</div><p className="mt-7 text-lg leading-8 text-muted-foreground">O Marcenapp conecta informações que fazem parte do mesmo trabalho.</p></div></div></div></section>

      <section className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-sm font-black uppercase tracking-[0.18em] text-primary">Para quem é</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">Feito para quem trabalha com móveis sob medida.</h2></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[['Marceneiros','Para quem projeta e produz seus próprios móveis.'],['Marcenarias','Para organizar projetos e informações de produção.'],['Projetistas','Para desenvolver projetos com mais organização.'],['Móveis planejados','Para centralizar as informações do projeto.']].map(([t,x])=><div key={t} className="rounded-3xl border border-primary/15 bg-card p-6 shadow-sm"><h3 className="font-black">{t}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{x}</p></div>)}</div></div></section>

      <section className="border-y border-border bg-primary/5 px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-sm font-black uppercase tracking-[0.18em] text-primary">Projetos reais</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">Veja o que pode ser desenvolvido no Marcenapp.</h2><p className="mt-5 text-lg leading-8 text-muted-foreground">Quando houver portfólio real disponível, esta área mostra projeto, visualização e resultado do mesmo trabalho.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{['Projeto','Visualização','Resultado'].map(x=><div key={x} className="flex min-h-56 items-end rounded-3xl border border-primary/15 bg-card p-5 shadow-sm"><div><span className="rounded-full bg-primary/10 px-3 py-1 text-[10px] font-black uppercase tracking-[0.16em] text-primary">{x}</span><p className="mt-3 text-sm font-semibold text-muted-foreground">Espaço preparado para imagens reais do produto.</p></div></div>)}</div></div></section>

      <section id="planos" className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-sm font-black uppercase tracking-[0.18em] text-primary">Planos</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">Use o Marcenapp do jeito que sua marcenaria trabalha.</h2><p className="mt-5 text-lg leading-8 text-muted-foreground">Escolha a opção disponível para sua operação e consulte as condições comerciais atuais antes de contratar.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{['Começar','Profissional','Marcenaria'].map((t,i)=><div key={t} className={`rounded-3xl border p-7 ${i===1?'border-primary bg-primary text-white shadow-lg shadow-primary/20':'border-primary/15 bg-card'}`}><p className={`text-xs font-black uppercase tracking-[0.16em] ${i===1?'text-blue-100':'text-primary/70'}`}>Opção {i+1}</p><h3 className="mt-3 text-2xl font-black">{t}</h3><p className={`mt-4 text-sm leading-6 ${i===1?'text-blue-100':'text-muted-foreground'}`}>Detalhes, créditos e condições conforme a configuração comercial atual do Marcenapp.</p><button onClick={goAuth} className={`mt-7 w-full rounded-2xl px-5 py-3.5 font-black ${i===1?'bg-white text-primary':'bg-primary text-white hover:bg-primary/90'}`}>Começar agora</button></div>)}</div></div></section>

      <section className="border-y border-border bg-card px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-4xl"><div className="text-center"><p className="text-sm font-black uppercase tracking-[0.18em] text-primary">FAQ</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">Perguntas frequentes.</h2></div><div className="mt-10 divide-y divide-border rounded-3xl border border-primary/15 bg-card">{faqs.map(([q,a],i)=><div key={q}><button className="flex w-full items-center justify-between gap-6 p-6 text-left font-black" onClick={()=>setOpenFaq(openFaq===i?null:i)}>{q}<ChevronDown size={19} className={`shrink-0 text-primary transition ${openFaq===i?'rotate-180':''}`}/></button>{openFaq===i&&<div className="px-6 pb-6 text-sm leading-7 text-muted-foreground">{a}</div>}</div>)}</div></div></section>

      <section className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-5xl rounded-[2rem] bg-slate-950 px-6 py-14 text-center text-white shadow-xl shadow-primary/10 sm:px-12"><p className="text-sm font-black uppercase tracking-[0.18em] text-blue-300">Comece pelo próximo projeto</p><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-6xl">Seu próximo projeto pode começar aqui.</h2><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-slate-300">Organize o projeto, desenvolva o móvel e reúna as informações necessárias para seguir para a produção.</p><button onClick={goAuth} className="mt-8 inline-flex items-center gap-2 rounded-2xl bg-primary px-7 py-4 font-black text-white hover:bg-primary/90">Começar agora <ArrowRight size={18}/></button><p className="mt-5 text-sm font-semibold text-blue-200">Do projeto à produção, tudo no lugar.</p></div></section>
    </main>
    <footer className="border-t border-border bg-card px-5 py-8 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-4 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between"><div className="font-black text-foreground">MARCENAPP</div><div>Do projeto à produção, tudo no lugar.</div></div></footer>
  </div>;
};
export default Landing;
