import { useEffect, useState } from 'react';
import { ArrowRight, Check, ChevronDown, CircleDollarSign, FileText, Hammer, Menu, Ruler, Sparkles, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import logo from '@/assets/marcenapp-logo.svg';
import { supabase } from '@/integrations/supabase/client';

interface Plan { id:string; code:string; name:string; description:string|null; monthly_price_cents:number|null; features:{ ai_messages_monthly?:number|null }|null }
interface Product { id:string; code:string; name:string; description:string|null; credits:number; price_cents:number|null }
const money=(v:number|null)=>v==null?'Preço a definir':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v/100);
function CabinetVisual(){return <div className="relative mx-auto w-full max-w-[560px] rounded-[32px] border border-white/10 bg-white/[.04] p-4 shadow-2xl"><div className="rounded-[24px] border border-white/10 bg-slate-900 p-4"><div className="mb-4 flex items-center justify-between text-[10px] font-bold uppercase tracking-[.18em] text-slate-400"><span>Projeto · Cozinha</span><span className="text-blue-300">IARA</span></div><div className="grid grid-cols-[.35fr_1fr] gap-3"><div className="space-y-2 rounded-2xl border border-white/10 bg-white/[.03] p-3"><div className="h-2 rounded bg-white/10"/><div className="h-2 rounded bg-white/10"/><div className="h-2 w-2/3 rounded bg-white/10"/><div className="mt-5 rounded-xl border border-blue-400/20 bg-blue-400/10 p-3"><p className="text-[8px] font-black uppercase tracking-widest text-blue-300">Ambiente</p><p className="mt-1 text-xs font-bold text-white">Cozinha</p></div></div><div className="relative min-h-[290px] overflow-hidden rounded-2xl border border-white/10 bg-gradient-to-br from-slate-700 via-slate-800 to-slate-950"><div className="absolute inset-x-8 bottom-8 top-10 border-2 border-slate-400/30"><div className="absolute inset-y-0 left-1/3 border-l border-slate-400/20"/><div className="absolute inset-y-0 right-1/3 border-l border-slate-400/20"/><div className="absolute inset-x-0 top-1/2 border-t border-slate-400/20"/><div className="absolute bottom-0 left-0 right-0 h-1/2 bg-white/[.035]"/></div><div className="absolute bottom-4 left-4 rounded-xl border border-white/10 bg-slate-950/80 px-3 py-2 backdrop-blur"><p className="text-[8px] font-black uppercase tracking-widest text-blue-300">Modelo do projeto</p><p className="mt-1 text-[11px] font-semibold text-white">Medidas · ambiente · módulos · materiais</p></div></div></div></div></div>}

export default function LandingV2(){
 const navigate=useNavigate(); const [menu,setMenu]=useState(false); const [plans,setPlans]=useState<Plan[]>([]); const [products,setProducts]=useState<Product[]>([]); const [faq,setFaq]=useState<number|null>(null);
 const signup=()=>navigate('/perfil-profissional'); const login=()=>navigate('/auth'); const buy=(code:string)=>navigate(`/auth?purchase=${encodeURIComponent(code)}`);
 useEffect(()=>{void Promise.all([supabase.from('billing_plans').select('id,code,name,description,monthly_price_cents,features').eq('status','active').order('sort_order'),supabase.from('billing_credit_products').select('id,code,name,description,credits,price_cents').eq('status','active').order('sort_order')]).then(([a,b])=>{setPlans((a.data??[]) as Plan[]);setProducts((b.data??[]) as Product[])});},[]);
 const faqs=[['Preciso começar com uma imagem?','Não. A IARA pode começar pelo texto e pelas medidas que você informar. Quando houver foto ou planta, ela usa essas referências para entender o ambiente.'],['A IARA substitui meu jeito de trabalhar?','Não. O projeto continua sendo seu. O objetivo é organizar contexto, acelerar tarefas e transformar informação em artefatos úteis para a marcenaria.'],['Posso usar só uma parte do Marcenapp?','Sim. As capacidades são conectadas, mas você pode usar documentação, orçamento, produção, render ou outras etapas conforme a necessidade do projeto.'],['Como funcionam os créditos?','Algumas operações que envolvem IA ou processamento pago consomem créditos. Você pode comprar avulso ou usar a franquia de um plano mensal.']];
 return <div className="min-h-screen bg-background text-foreground">
  <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-slate-950/90 text-white backdrop-blur-xl"><div className="mx-auto flex h-[72px] max-w-7xl items-center justify-between px-5 lg:px-8"><button onClick={()=>window.scrollTo({top:0,behavior:'smooth'})} className="flex items-center gap-3"><img src={logo} alt="Marcenapp" className="h-9 w-9 rounded-xl"/><span className="font-black tracking-tight">MARCENAPP</span></button><nav className="hidden items-center gap-7 md:flex"><a href="#produto" className="text-sm font-semibold text-slate-300 hover:text-white">Produto</a><a href="#fluxo" className="text-sm font-semibold text-slate-300 hover:text-white">Como funciona</a><a href="#recursos" className="text-sm font-semibold text-slate-300 hover:text-white">Recursos</a><a href="#valores" className="text-sm font-semibold text-slate-300 hover:text-white">Valores</a><button onClick={login} className="rounded-xl px-3 py-2 text-sm font-bold">Entrar</button><button onClick={signup} className="rounded-xl bg-white px-5 py-2.5 text-sm font-black text-slate-950">Começar agora</button></nav><button onClick={()=>setMenu(!menu)} className="rounded-xl p-2 md:hidden" aria-label={menu?'Fechar menu':'Abrir menu'}>{menu?<X/>:<Menu/>}</button></div>{menu&&<div className="border-t border-white/10 bg-slate-950 px-5 py-4 md:hidden"><div className="flex flex-col gap-1">{[['produto','Produto'],['fluxo','Como funciona'],['recursos','Recursos'],['valores','Valores'],['duvidas','Dúvidas']].map(([id,label])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)} className="rounded-xl px-3 py-3 font-semibold text-slate-300">{label}</a>)}<button onClick={signup} className="mt-2 rounded-xl bg-white px-4 py-3 font-black text-slate-950">Começar agora</button></div></div>}</header>
  <main>
   <section id="produto" className="overflow-hidden bg-slate-950 px-5 pb-20 pt-32 text-white lg:px-8 lg:pb-28 lg:pt-40"><div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[.9fr_1.1fr]"><div><p className="mb-5 text-xs font-black uppercase tracking-[.2em] text-blue-300">Tecnologia para quem projeta e produz</p><h1 className="max-w-3xl text-5xl font-black leading-[.94] tracking-[-.055em] sm:text-6xl lg:text-7xl">Sua marcenaria trabalha.<br/><span className="text-blue-300">A IARA acelera.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-300">Do que você registra no cliente ao que precisa chegar na produção: projeto, contexto, visual, documentação, orçamento e operação conectados.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><button onClick={signup} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-white px-7 py-4 font-black text-slate-950">Começar agora <ArrowRight size={18}/></button><a href="#fluxo" className="inline-flex items-center justify-center rounded-2xl border border-white/15 px-7 py-4 font-bold text-white">Ver como funciona</a></div><p className="mt-6 text-xs font-semibold text-slate-500">Cadastro gratuito. Recursos pagos usam créditos.</p></div><CabinetVisual/></div></section>
   <section id="fluxo" className="bg-background px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-xs font-black uppercase tracking-[.2em] text-primary">Um contexto, várias capacidades</p><h2 className="mt-3 text-4xl font-black tracking-tight text-slate-950">Você não precisa recomeçar o projeto a cada etapa.</h2><p className="mt-4 text-base leading-7 text-slate-500">O Marcenapp organiza o projeto como uma fonte única de contexto. A IARA trabalha em cima dele e entrega a próxima informação útil.</p></div><div className="mt-12 grid gap-px overflow-hidden rounded-3xl border border-slate-200 bg-slate-200 md:grid-cols-5">{[['01','Diário','Registro de campo'],['02','Projeto','Contexto e medidas'],['03','IARA','Análise e ação'],['04','Artefato','Visual, técnico ou orçamento'],['05','Produção','Informação pronta para avançar']].map(([n,t,s])=><div key={n} className="bg-white p-6"><span className="text-[10px] font-black tracking-widest text-slate-400">{n}</span><h3 className="mt-8 text-lg font-black text-slate-950">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{s}</p></div>)}</div></div></section>
   <section id="recursos" className="bg-slate-50 px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-xs font-black uppercase tracking-[.2em] text-primary">Feito para a rotina real</p><h2 className="mt-3 text-4xl font-black tracking-tight text-slate-950">Menos trabalho repetido. Mais informação aproveitável.</h2></div><p className="max-w-md text-sm leading-6 text-slate-500">Use somente o que a obra precisa. O restante pode entrar depois, sem perder o contexto.</p></div><div className="mt-12 grid gap-4 md:grid-cols-3">{[[FileText,'Documentação técnica','Plantas, vistas, cortes e cotas a partir do modelo do projeto.'],[CircleDollarSign,'Orçamento','Leve medidas, materiais e decisões do projeto para o orçamento.'],[Hammer,'Produção','Organize materiais, ferragens, corte e informações para a oficina.'],[Ruler,'Medidas e ambiente','Trabalhe com medidas informadas, fotos e plantas sem inventar o que não foi validado.'],[Sparkles,'IARA','Converse por texto, foto ou contexto do projeto e avance a próxima ação.'],[Check,'Revisão do cliente','Envie um link para aprovar ou solicitar alterações antes de liberar a produção.']].map(([Icon,title,text])=>{const C=Icon as typeof FileText;return <article key={String(title)} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-slate-950 text-white"><C size={19}/></div><h3 className="mt-5 text-lg font-black text-slate-950">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{String(text)}</p></article>})}</div></div></section>
   <section id="valores" className="bg-slate-950 px-5 py-20 text-white lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-xs font-black uppercase tracking-[.2em] text-blue-300">Valores</p><h2 className="mt-3 text-4xl font-black tracking-tight">Use a capacidade que fizer sentido para a obra.</h2><p className="mt-4 text-base leading-7 text-slate-400">Sem obrigar sua marcenaria a comprar um fluxo fechado.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{products.slice(0,3).map(p=><article key={p.id} className="rounded-3xl border border-white/10 bg-white/[.05] p-6"><p className="text-xs font-black uppercase tracking-widest text-blue-300">Compra avulsa</p><h3 className="mt-3 text-xl font-black">{p.name}</h3><p className="mt-2 min-h-12 text-sm leading-6 text-slate-400">{p.description}</p><div className="mt-6 flex items-end justify-between gap-3"><div><p className="text-2xl font-black">{money(p.price_cents)}</p><p className="text-xs text-slate-500">{p.credits} crédito</p></div><button onClick={()=>buy(p.code)} className="rounded-xl bg-white px-4 py-2.5 text-sm font-black text-slate-950">Comprar</button></div></article>)}</div>{plans.length>0&&<div className="mt-5 grid gap-4 md:grid-cols-3">{plans.slice(0,3).map(p=><article key={p.id} className="rounded-3xl border border-white/10 bg-slate-900 p-6"><p className="text-xs font-black uppercase tracking-widest text-slate-500">Plano mensal</p><h3 className="mt-2 text-xl font-black">{p.name.replace('MARCENAPP ','')}</h3><p className="mt-5 text-2xl font-black">{money(p.monthly_price_cents)}<span className="text-xs font-bold text-slate-500">/mês</span></p><p className="mt-3 text-sm leading-6 text-slate-400">{p.description}</p><button onClick={()=>buy(p.code)} className="mt-6 inline-flex w-full items-center justify-center rounded-xl border border-white/15 px-4 py-3 text-sm font-black text-white">Escolher plano</button></article>)}</div>}</div></section>
   <section id="duvidas" className="bg-background px-5 py-20 lg:px-8 lg:py-24"><div className="mx-auto max-w-4xl"><p className="text-xs font-black uppercase tracking-[.2em] text-primary">Dúvidas</p><h2 className="mt-3 text-4xl font-black tracking-tight text-slate-950">Antes de começar</h2><div className="mt-8 divide-y divide-slate-200 rounded-3xl border border-slate-200 bg-white">{faqs.map(([q,a],i)=><div key={q}><button onClick={()=>setFaq(faq===i?null:i)} className="flex w-full items-center justify-between gap-5 px-6 py-5 text-left font-black text-slate-900"><span>{q}</span><ChevronDown size={18} className={`shrink-0 transition-transform ${faq===i?'rotate-180':''}`}/></button>{faq===i&&<p className="px-6 pb-5 text-sm leading-7 text-slate-500">{a}</p>}</div>)}</div></div></section>
  </main>
  <footer className="border-t border-slate-200 bg-white px-5 py-8"><div className="mx-auto flex max-w-7xl flex-col gap-3 text-xs text-slate-400 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-2"><img src={logo} alt="Marcenapp" className="h-6 w-6 rounded-lg"/><span className="font-black text-slate-700">MARCENAPP</span></div><span>Do projeto à produção, tudo no lugar.</span></div></footer>
 </div>
}