import { ArrowRight, Check, ChevronDown, Menu, X } from 'lucide-react';
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import logo from '@/assets/marcenapp-logo.svg';

const heroImage = 'https://images.unsplash.com/photo-1542302760-b1db9d8c64e6?auto=format&fit=crop&fm=jpg&q=80&w=1600';
const workflowImage = 'https://images.unsplash.com/photo-1618832515490-e181c4794a45?auto=format&fit=crop&fm=jpg&q=80&w=1600';
const productImage = 'https://images.unsplash.com/photo-1781871522095-3bb9439f3bbe?auto=format&fit=crop&fm=jpg&q=80&w=1600';

const resources = [
  ['Projeto','Organize cada projeto em um único ambiente.'],['Ambiente','Estruture o ambiente antes de desenvolver o móvel.'],
  ['Dimensionamento','Trabalhe com as medidas do móvel de forma organizada.'],['2D e 3D','Veja o projeto antes de produzir.'],
  ['Materiais','Organize os materiais usados no projeto.'],['Ferragens','Mantenha as ferragens associadas ao projeto.'],
  ['Lista de corte','Transforme o projeto em informação para produção.'],['Orçamento','Leve as informações do projeto para o orçamento.'],
];
const flow = [['01','Na casa do cliente','Faça as medidas, registre fotos e reúna as informações do ambiente.'],['02','No celular','Tenha fotos, medidas e observações organizadas no momento da visita.'],['03','No Marcenapp','Desenvolva o projeto no computador com visualização 2D e 3D.'],['04','Confira o resultado','Visualize o mesmo ambiente antes de produzir.'],['05','Siga para a produção','Reúna as informações necessárias para as próximas etapas.']];
const faqs = [
 ['O que é o Marcenapp?','Uma plataforma para profissionais de marcenaria que reúne projeto, dimensionamento, visualização, materiais, ferragens, lista de corte e orçamento em um único fluxo de trabalho.'],
 ['Para quem ele foi desenvolvido?','Para quem trabalha com móveis sob medida: marceneiros, marcenarias, projetistas e profissionais de móveis planejados.'],
 ['Preciso saber trabalhar em 3D?','O Marcenapp permite acompanhar o desenvolvimento do projeto e visualizá-lo em 2D e 3D antes da produção.'],
 ['O que é a Yara?','A Yara é a assistente de inteligência artificial do Marcenapp. Ela ajuda a interpretar informações e acompanhar etapas do projeto.'],
 ['O Marcenapp gera lista de corte?','O sistema reúne as informações do projeto necessárias para preparar a etapa de corte, conforme os recursos disponíveis.'],
 ['Como funcionam os créditos?','Os detalhes de créditos e condições devem ser consultados na configuração comercial atual da plataforma.'],
];

export default function Landing() {
 const navigate=useNavigate(); const [menu,setMenu]=useState(false); const [faq,setFaq]=useState<number|null>(null); const go=()=>navigate('/auth');
 return <div className="min-h-screen overflow-x-hidden bg-background text-foreground">
  <header className="fixed inset-x-0 top-0 z-50 border-b border-border/80 bg-background/95 backdrop-blur"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8">
   <button onClick={()=>window.scrollTo({top:0,behavior:'smooth'})} className="flex items-center gap-3"><img src={logo} alt="Marcenapp" className="h-10 w-10 rounded-xl"/><span className="text-lg font-black tracking-tight">MARCENAPP</span></button>
   <nav className="hidden items-center gap-7 md:flex"><a href="#recursos" className="text-sm font-semibold text-muted-foreground hover:text-primary">Recursos</a><a href="#fluxo" className="text-sm font-semibold text-muted-foreground hover:text-primary">Como funciona</a><a href="#yara" className="text-sm font-semibold text-muted-foreground hover:text-primary">Yara</a><a href="#planos" className="text-sm font-semibold text-muted-foreground hover:text-primary">Planos</a><button onClick={go} className="rounded-xl px-4 py-2 text-sm font-bold">Entrar</button><button onClick={go} className="rounded-xl bg-primary px-5 py-2.5 text-sm font-black text-primary-foreground">Começar agora</button></nav>
   <button className="rounded-xl p-2 md:hidden" onClick={()=>setMenu(!menu)} aria-label="Abrir menu">{menu?<X/>:<Menu/>}</button>
  </div>{menu&&<div className="border-t border-border bg-background px-5 py-4 md:hidden"><div className="flex flex-col gap-1">{['#recursos','#fluxo','#yara','#planos'].map(h=><a key={h} href={h} onClick={()=>setMenu(false)} className="rounded-xl px-3 py-3 font-semibold text-muted-foreground">{h.replace('#','')}</a>)}<button onClick={go} className="mt-2 rounded-xl bg-primary px-4 py-3 font-black text-primary-foreground">Entrar ou começar</button></div></div>}</header>
  <main>
   <section className="px-5 pb-20 pt-32 lg:px-8 lg:pb-28 lg:pt-40"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[.82fr_1.18fr]"><div><p className="mb-5 text-sm font-black uppercase tracking-[.18em] text-primary">Do projeto à produção, tudo no lugar.</p><h1 className="max-w-2xl text-5xl font-black leading-[.98] tracking-[-.045em] sm:text-6xl lg:text-7xl">Do projeto à produção, <span className="text-primary">tudo no lugar.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-muted-foreground sm:text-xl">Desenvolva seus projetos de marcenaria, visualize em 2D e 3D e organize medidas, materiais, ferragens, lista de corte e orçamento em um único fluxo de trabalho.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><button onClick={go} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-primary px-7 py-4 font-black text-primary-foreground">Começar agora <ArrowRight size={18}/></button><a href="#historia" className="inline-flex items-center justify-center rounded-2xl border border-primary/20 bg-card px-7 py-4 font-bold">Conhecer o Marcenapp</a></div><p className="mt-5 text-sm font-medium text-muted-foreground">Feito para quem projeta e produz móveis sob medida.</p></div><div className="overflow-hidden rounded-[2rem] border border-primary/15 bg-card shadow-xl"><img src={heroImage} alt="Marceneiro registrando o ambiente do cliente pelo celular" className="h-[420px] w-full object-cover"/></div></div></section>
   <section id="historia" className="border-y border-border bg-card px-5 py-20 lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-sm font-black uppercase tracking-[.18em] text-primary">A jornada real</p><h2 className="mt-3 max-w-3xl text-3xl font-black tracking-tight sm:text-5xl">Um projeto de marcenaria não termina no desenho.</h2></div><p className="max-w-md text-muted-foreground">A mesma informação acompanha você da visita ao cliente até a preparação para a produção.</p></div><div className="mt-12 overflow-hidden rounded-3xl border border-border"><img src={workflowImage} alt="Ambiente de marcenaria em desenvolvimento" className="h-[360px] w-full object-cover"/></div><div className="mt-8 grid gap-4 md:grid-cols-5">{flow.map(([n,t,tx])=><div key={n} className="rounded-2xl border border-primary/10 bg-primary/[.035] p-5"><div className="text-sm font-black text-primary">{n}</div><h3 className="mt-3 font-black">{t}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{tx}</p></div>)}</div></div></section>
   <section className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="text-sm font-black uppercase tracking-[.18em] text-primary">O problema</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">Um projeto de marcenaria não termina no desenho.</h2><p className="mt-5 text-lg leading-8 text-muted-foreground">Depois do desenho ainda existem medidas, materiais, ferragens, cortes, orçamento e muitas outras informações que precisam estar organizadas.</p><p className="mt-4 text-lg font-bold leading-8">O desafio não é apenas projetar o móvel. É organizar tudo o que vem junto com ele.</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{['Projeto','Medidas','Materiais','Ferragens','Corte','Orçamento'].map(x=><div key={x} className="rounded-2xl border border-border bg-card p-5"><Check className="text-primary"/><p className="mt-5 font-black">{x}</p><p className="mt-1 text-sm text-muted-foreground">Informação no fluxo do projeto.</p></div>)}</div></div></section>
   <section className="border-y border-primary/15 bg-primary/[.035] px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><div><p className="text-sm font-black uppercase tracking-[.18em] text-primary">A solução</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">Uma ferramenta pensada para o trabalho real da marcenaria.</h2><p className="mt-5 text-lg leading-8 text-muted-foreground">Menos informação espalhada. Mais clareza em cada etapa do projeto.</p></div><div className="overflow-hidden rounded-3xl border border-primary/15 bg-card shadow-lg"><img src={productImage} alt="Computador e celular em um ambiente de trabalho" className="h-[360px] w-full object-cover"/></div></div></section>
   <section id="recursos" className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><p className="text-sm font-black uppercase tracking-[.18em] text-primary">O produto</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">Um projeto. Um fluxo de trabalho.</h2><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{resources.map(([t,tx],i)=><div key={t} className="rounded-2xl border border-border bg-card p-6"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-sm font-black text-primary">{String(i+1).padStart(2,'0')}</div><h3 className="mt-5 font-black">{t}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{tx}</p></div>)}</div></div></section>
   <section id="fluxo" className="bg-slate-950 px-5 py-20 text-white lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-sm font-black uppercase tracking-[.18em] text-amber-400">Do projeto à produção</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">Mais do que projetar. Organize o caminho até a produção.</h2><p className="mt-5 text-lg leading-8 text-slate-300">Menos informação espalhada. Mais clareza para acompanhar cada etapa.</p></div><div className="space-y-3">{flow.map(([n,t,tx])=><div key={n} className="grid gap-4 rounded-2xl border border-white/10 bg-white/[.04] p-5 sm:grid-cols-[48px_190px_1fr] sm:items-center"><span className="font-black text-amber-400">{n}</span><strong>{t}</strong><span className="text-sm leading-6 text-slate-300">{tx}</span></div>)}</div></div></section>
   <section id="yara" className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl rounded-3xl border border-primary/15 bg-card p-8 sm:p-12"><p className="text-sm font-black uppercase tracking-[.18em] text-primary">Yara</p><h2 className="mt-3 max-w-2xl text-3xl font-black tracking-tight sm:text-5xl">Você continua no controle. A Yara ajuda no processo.</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-muted-foreground">A Yara é a assistente de inteligência artificial do Marcenapp. Ela ajuda a interpretar informações e acompanhar etapas do projeto dentro do fluxo de trabalho.</p><div className="mt-7 flex items-center gap-3 font-bold"><Check className="text-primary"/> A tecnologia apoia o trabalho. Você continua decidindo.</div></div></section>
   <section id="planos" className="border-y border-border bg-card px-5 py-20 lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><p className="text-sm font-black uppercase tracking-[.18em] text-primary">Planos / acesso</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">Use o Marcenapp do jeito que sua marcenaria trabalha.</h2><p className="mt-5 max-w-2xl text-lg text-muted-foreground">Consulte as opções e condições comerciais atuais da plataforma antes de começar.</p><button onClick={go} className="mt-8 rounded-2xl bg-primary px-7 py-4 font-black text-primary-foreground">Começar agora <ArrowRight className="ml-2 inline" size={18}/></button></div></section>
   <section className="px-5 py-20 lg:px-8 lg:py-24"><div className="mx-auto max-w-4xl"><p className="text-sm font-black uppercase tracking-[.18em] text-primary">Perguntas frequentes</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">Perguntas frequentes sobre o Marcenapp.</h2><div className="mt-10 divide-y divide-border border-y border-border">{faqs.map(([q,a],i)=><div key={q}><button onClick={()=>setFaq(faq===i?null:i)} className="flex w-full items-center justify-between gap-4 py-5 text-left font-black">{q}<ChevronDown className={`shrink-0 transition-transform ${faq===i?'rotate-180':''}`}/></button>{faq===i&&<p className="pb-5 pr-8 leading-7 text-muted-foreground">{a}</p>}</div>)}</div></div></section>
   <section className="bg-slate-950 px-5 py-20 text-center text-white lg:px-8 lg:py-24"><h2 className="text-3xl font-black sm:text-5xl">Seu próximo projeto pode começar aqui.</h2><p className="mx-auto mt-5 max-w-2xl text-lg text-slate-300">Organize o projeto, desenvolva o móvel e reúna as informações necessárias para seguir para a produção.</p><button onClick={go} className="mt-8 rounded-2xl bg-primary px-8 py-4 font-black text-white">Começar agora <ArrowRight className="ml-2 inline" size={18}/></button></section>
  </main><footer className="border-t border-border px-5 py-8"><div className="mx-auto flex max-w-7xl flex-col gap-3 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between"><span className="font-black text-foreground">MARCENAPP</span><span>Do projeto à produção, tudo no lugar.</span></div></footer>
 </div>;
}
