import { ArrowRight, Check, ChevronDown, Menu, Ruler, Layers3, PackageCheck, X } from 'lucide-react';
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import logo from '@/assets/marcenapp-logo.svg';

const resources = [
  ['Projeto','Organize cada projeto em um único ambiente.'],['Ambiente','Estruture o ambiente antes de desenvolver o móvel.'],
  ['Dimensionamento','Trabalhe com as medidas do móvel de forma organizada.'],['2D e 3D','Veja o projeto antes de produzir.'],
  ['Materiais','Organize os materiais usados no projeto.'],['Ferragens','Mantenha as ferragens associadas ao projeto.'],
  ['Lista de corte','Transforme o projeto em informação para produção.'],['Orçamento','Leve as informações do projeto para o orçamento.'],
];
const flow = [['01','Na casa do cliente','Faça as medidas, registre fotos e reúna as informações do ambiente.'],['02','No celular','Tenha fotos, medidas e observações organizadas no momento da visita.'],['03','No Marcenapp','Desenvolva o projeto no computador com visualização 2D e 3D.'],['04','Confira o resultado','Visualize o mesmo ambiente antes de produzir.'],['05','Siga para a produção','Reúna as informações necessárias para as próximas etapas.']];
const faqs = [
 ['O que é o Marcenapp?','Uma plataforma para profissionais de marcenaria que reúne projeto, dimensionamento, visualização, materiais, ferragens, lista de corte e orçamento em um único fluxo de trabalho.'],
 ['Para quem ele foi desenvolvido?','Para quem trabalha com móveis sob medida: marceneiros, marcenarias, projetistas e profissionais de móveis planejados.'],
 ['Preciso saber trabalhar em 3D?','O Marcenapp permite acompanhar o desenvolvimento do projeto e visualizá-lo em 2D e 3D antes da produção.'],
 ['O que é a Yara?','A Yara é a assistente de inteligência artificial do Marcenapp. Ela ajuda a interpretar informações e acompanhar etapas do projeto.'],
 ['O Marcenapp gera lista de corte?','O sistema reúne as informações do projeto necessárias para preparar a etapa de corte, conforme os recursos disponíveis.'],
 ['Como funcionam os créditos?','Os detalhes de créditos e condições devem ser consultados na configuração comercial atual da plataforma.'],
];

function ProjectVisual({ variant = 'hero' }: { variant?: 'hero' | 'workflow' | 'product' }) {
  if (variant === 'workflow') return <div className="brand-grid relative h-[360px] overflow-hidden bg-white p-5 sm:p-8">
    <div className="absolute left-[10%] top-[16%] h-[64%] w-[30%] rounded-xl border-2 border-primary/30 bg-primary/[.035]" />
    <div className="absolute left-[44%] top-[16%] h-[64%] w-[46%] rounded-xl border-2 border-primary/20 bg-white shadow-sm" />
    <div className="absolute left-[14%] top-[23%] h-3 w-20 rounded-full bg-primary/15" />
    <div className="absolute left-[14%] top-[34%] h-20 w-[20%] rounded-lg border border-border bg-card" />
    <div className="absolute left-[48%] top-[24%] h-4 w-28 rounded-full bg-primary/15" />
    <div className="absolute left-[48%] top-[35%] h-24 w-[36%] rounded-lg border border-border bg-card" />
    <div className="absolute bottom-[18%] left-[48%] flex gap-2"><span className="rounded-lg bg-primary/10 px-3 py-2 text-xs font-bold text-primary">Medidas</span><span className="rounded-lg bg-primary/10 px-3 py-2 text-xs font-bold text-primary">Materiais</span><span className="rounded-lg bg-primary/10 px-3 py-2 text-xs font-bold text-primary">Corte</span></div>
    <div className="absolute left-[22%] top-[9%] flex items-center gap-2 text-[11px] font-bold text-muted-foreground"><Ruler size={14} className="text-primary"/> ambiente organizado</div>
  </div>;

  if (variant === 'product') return <div className="relative h-[360px] overflow-hidden bg-slate-950 p-5 text-white sm:p-8">
    <div className="absolute inset-5 rounded-2xl border border-white/10 bg-white/[.04] p-4 sm:inset-8">
      <div className="flex items-center justify-between border-b border-white/10 pb-3"><span className="text-xs font-extrabold tracking-wide">MARCENAPP / PROJETO</span><span className="rounded-md bg-primary px-2 py-1 text-[10px] font-bold">ATIVO</span></div>
      <div className="grid h-[calc(100%-44px)] grid-cols-[1.2fr_.8fr] gap-3 pt-4">
        <div className="brand-grid rounded-xl border border-white/10 bg-white/[.03] p-4"><div className="mx-auto mt-3 h-36 w-[72%] rounded-lg border-2 border-white/20 bg-white/[.025] sm:h-44"><div className="mx-auto mt-8 h-16 w-[76%] rounded-md border border-primary/50 bg-primary/10" /><div className="mx-auto mt-3 h-1 w-[55%] rounded bg-white/20" /></div><div className="mt-4 flex justify-center gap-2 text-[10px] text-slate-300"><span>2D</span><span>•</span><span>3D</span><span>•</span><span>medidas</span></div></div>
        <div className="space-y-2"><div className="rounded-xl border border-white/10 bg-white/[.04] p-3"><div className="flex items-center gap-2 text-xs font-bold"><Layers3 size={14} className="text-primary"/> Materiais</div><p className="mt-2 text-[10px] text-slate-400">MDF, ferragens e acabamentos</p></div><div className="rounded-xl border border-white/10 bg-white/[.04] p-3"><div className="flex items-center gap-2 text-xs font-bold"><PackageCheck size={14} className="text-primary"/> Produção</div><p className="mt-2 text-[10px] text-slate-400">Lista de corte organizada</p></div><div className="rounded-xl border border-primary/30 bg-primary/10 p-3"><div className="text-[10px] font-bold text-blue-200">Yara</div><p className="mt-1 text-[10px] text-slate-300">Ajuda no processo. Você continua no controle.</p></div></div>
      </div>
    </div>
  </div>;

  return <div className="brand-grid relative h-[420px] overflow-hidden bg-white p-5 sm:p-8">
    <div className="absolute inset-5 rounded-[1.5rem] border border-primary/15 bg-white shadow-2xl sm:inset-8" />
    <div className="absolute left-[9%] top-[13%] rounded-xl border border-border bg-card px-3 py-2 text-[10px] font-extrabold text-foreground shadow-sm">PROJETO / COZINHA</div>
    <div className="absolute left-[12%] top-[28%] h-[50%] w-[48%] rounded-xl border-2 border-primary/30 bg-primary/[.025] shadow-sm">
      <div className="absolute left-[10%] top-[14%] h-[26%] w-[80%] rounded-md border border-primary/25 bg-white" />
      <div className="absolute left-[10%] top-[48%] h-[34%] w-[35%] rounded-md border border-primary/25 bg-primary/[.06]" />
      <div className="absolute right-[10%] top-[48%] h-[34%] w-[35%] rounded-md border border-primary/25 bg-primary/[.06]" />
      <div className="absolute -left-5 top-1/2 h-px w-4 bg-primary/50" /><div className="absolute -right-5 top-1/2 h-px w-4 bg-primary/50" />
    </div>
    <div className="absolute right-[10%] top-[24%] w-[25%] rounded-xl border border-border bg-card p-4 shadow-lg">
      <div className="text-[10px] font-extrabold text-muted-foreground">DIMENSIONAMENTO</div><div className="mt-3 h-2 w-20 rounded bg-primary/20" /><div className="mt-3 space-y-2"><div className="flex justify-between text-[10px]"><span>largura</span><b>2.40 m</b></div><div className="flex justify-between text-[10px]"><span>altura</span><b>2.20 m</b></div><div className="flex justify-between text-[10px]"><span>prof.</span><b>0.60 m</b></div></div>
    </div>
    <div className="absolute bottom-[13%] left-[12%] flex gap-2"><span className="rounded-lg bg-primary px-3 py-2 text-[10px] font-extrabold text-white">2D</span><span className="rounded-lg border border-primary/20 bg-white px-3 py-2 text-[10px] font-extrabold text-primary">3D</span><span className="rounded-lg border border-border bg-white px-3 py-2 text-[10px] font-bold">Lista de corte</span></div>
  </div>;
}

export default function Landing() {
 const navigate=useNavigate(); const [menu,setMenu]=useState(false); const [faq,setFaq]=useState<number|null>(null); const go=()=>navigate('/auth');
 return <div className="min-h-screen overflow-x-hidden bg-background text-foreground">
  <header className="fixed inset-x-0 top-0 z-50 border-b border-border/80 bg-background/95 backdrop-blur"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8">
   <button onClick={()=>window.scrollTo({top:0,behavior:'smooth'})} className="flex items-center gap-3"><img src={logo} alt="Marcenapp" className="h-10 w-10 rounded-xl"/><span className="text-lg font-extrabold tracking-[-.03em]">MARCENAPP</span></button>
   <nav className="hidden items-center gap-7 md:flex"><a href="#recursos" className="text-sm font-semibold text-muted-foreground hover:text-primary">Recursos</a><a href="#fluxo" className="text-sm font-semibold text-muted-foreground hover:text-primary">Como funciona</a><a href="#yara" className="text-sm font-semibold text-muted-foreground hover:text-primary">Yara</a><a href="#planos" className="text-sm font-semibold text-muted-foreground hover:text-primary">Planos</a><button onClick={go} className="rounded-xl px-4 py-2 text-sm font-bold">Entrar</button><button onClick={go} className="rounded-xl bg-primary px-5 py-2.5 text-sm font-extrabold text-primary-foreground">Começar agora</button></nav>
   <button className="rounded-xl p-2 md:hidden" onClick={()=>setMenu(!menu)} aria-label="Abrir menu">{menu?<X/>:<Menu/>}</button>
  </div>{menu&&<div className="border-t border-border bg-background px-5 py-4 md:hidden"><div className="flex flex-col gap-1">{['#recursos','#fluxo','#yara','#planos'].map(h=><a key={h} href={h} onClick={()=>setMenu(false)} className="rounded-xl px-3 py-3 font-semibold text-muted-foreground">{h.replace('#','')}</a>)}<button onClick={go} className="mt-2 rounded-xl bg-primary px-4 py-3 font-extrabold text-primary-foreground">Entrar ou começar</button></div></div>}</header>
  <main>
   <section className="px-5 pb-20 pt-32 lg:px-8 lg:pb-28 lg:pt-40"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[.82fr_1.18fr]"><div><p className="mb-5 text-sm font-extrabold uppercase tracking-[.18em] text-primary">Do projeto à produção, tudo no lugar.</p><h1 className="max-w-2xl text-5xl font-extrabold leading-[.98] tracking-[-.055em] sm:text-6xl lg:text-7xl">Do projeto à produção, <span className="text-primary">tudo no lugar.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-muted-foreground sm:text-xl">Desenvolva seus projetos de marcenaria, visualize em 2D e 3D e organize medidas, materiais, ferragens, lista de corte e orçamento em um único fluxo de trabalho.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><button onClick={go} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-primary px-7 py-4 font-extrabold text-primary-foreground">Começar agora <ArrowRight size={18}/></button><a href="#historia" className="inline-flex items-center justify-center rounded-2xl border border-primary/20 bg-card px-7 py-4 font-bold">Conhecer o Marcenapp</a></div><p className="mt-5 text-sm font-medium text-muted-foreground">Feito para quem projeta e produz móveis sob medida.</p></div><div className="overflow-hidden rounded-[2rem] border border-primary/15 bg-card brand-panel-shadow"><ProjectVisual/></div></div></section>
   <section id="historia" className="border-y border-border bg-card px-5 py-20 lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-sm font-extrabold uppercase tracking-[.18em] text-primary">A jornada real</p><h2 className="mt-3 max-w-3xl text-3xl font-extrabold tracking-tight sm:text-5xl">Um projeto de marcenaria não termina no desenho.</h2></div><p className="max-w-md text-muted-foreground">A mesma informação acompanha você da visita ao cliente até a preparação para a produção.</p></div><div className="mt-12 overflow-hidden rounded-3xl border border-border brand-panel-shadow"><ProjectVisual variant="workflow"/></div><div className="mt-8 grid gap-4 md:grid-cols-5">{flow.map(([n,t,tx])=><div key={n} className="rounded-2xl border border-primary/10 bg-primary/[.035] p-5"><div className="text-sm font-extrabold text-primary">{n}</div><h3 className="mt-3 font-extrabold">{t}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{tx}</p></div>)}</div></div></section>
   <section className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="text-sm font-extrabold uppercase tracking-[.18em] text-primary">O problema</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight sm:text-5xl">Um projeto de marcenaria não termina no desenho.</h2><p className="mt-5 text-lg leading-8 text-muted-foreground">Depois do desenho ainda existem medidas, materiais, ferragens, cortes, orçamento e muitas outras informações que precisam estar organizadas.</p><p className="mt-4 text-lg font-bold leading-8">O desafio não é apenas projetar o móvel. É organizar tudo o que vem junto com ele.</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{['Projeto','Medidas','Materiais','Ferragens','Corte','Orçamento'].map(x=><div key={x} className="rounded-2xl border border-border bg-card p-5"><Check className="text-primary"/><p className="mt-5 font-extrabold">{x}</p><p className="mt-1 text-sm text-muted-foreground">Informação no fluxo do projeto.</p></div>)}</div></div></section>
   <section className="border-y border-primary/15 bg-primary/[.035] px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><div><p className="text-sm font-extrabold uppercase tracking-[.18em] text-primary">A solução</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight sm:text-5xl">Uma ferramenta pensada para o trabalho real da marcenaria.</h2><p className="mt-5 text-lg leading-8 text-muted-foreground">Menos informação espalhada. Mais clareza em cada etapa do projeto.</p></div><div className="overflow-hidden rounded-3xl border border-primary/15 bg-card brand-panel-shadow"><ProjectVisual variant="product"/></div></div></section>
   <section id="recursos" className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><p className="text-sm font-extrabold uppercase tracking-[.18em] text-primary">O produto</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight sm:text-5xl">Um projeto. Um fluxo de trabalho.</h2><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{resources.map(([t,tx],i)=><div key={t} className="rounded-2xl border border-border bg-card p-6"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-sm font-extrabold text-primary">{String(i+1).padStart(2,'0')}</div><h3 className="mt-5 font-extrabold">{t}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{tx}</p></div>)}</div></div></section>
   <section id="fluxo" className="bg-slate-950 px-5 py-20 text-white lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-sm font-extrabold uppercase tracking-[.18em] text-blue-300">Do projeto à produção</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight sm:text-5xl">Mais do que projetar. Organize o caminho até a produção.</h2><p className="mt-5 text-lg leading-8 text-slate-300">Menos informação espalhada. Mais clareza para acompanhar cada etapa.</p></div><div className="space-y-3">{flow.map(([n,t,tx])=><div key={n} className="grid gap-4 rounded-2xl border border-white/10 bg-white/[.04] p-5 sm:grid-cols-[48px_190px_1fr] sm:items-center"><span className="font-extrabold text-blue-300">{n}</span><strong>{t}</strong><span className="text-sm leading-6 text-slate-300">{tx}</span></div>)}</div></div></section>
   <section id="yara" className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl rounded-3xl border border-primary/15 bg-card p-8 sm:p-12"><p className="text-sm font-extrabold uppercase tracking-[.18em] text-primary">Yara</p><h2 className="mt-3 max-w-2xl text-3xl font-extrabold tracking-tight sm:text-5xl">Você continua no controle. A Yara ajuda no processo.</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-muted-foreground">A Yara é a assistente de inteligência artificial do Marcenapp. Ela ajuda a interpretar informações e acompanhar etapas do projeto dentro do fluxo de trabalho.</p><div className="mt-7 flex items-center gap-3 font-bold"><Check className="text-primary"/> A tecnologia apoia o trabalho. Você continua decidindo.</div></div></section>
   <section id="planos" className="border-y border-border bg-card px-5 py-20 lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><p className="text-sm font-extrabold uppercase tracking-[.18em] text-primary">Planos / acesso</p><h2 className="mt-3 text-3xl font-extrabold sm:text-5xl">Use o Marcenapp do jeito que sua marcenaria trabalha.</h2><p className="mt-5 max-w-2xl text-lg text-muted-foreground">Consulte as opções e condições comerciais atuais da plataforma antes de começar.</p><button onClick={go} className="mt-8 rounded-2xl bg-primary px-7 py-4 font-extrabold text-primary-foreground">Começar agora <ArrowRight className="ml-2 inline" size={18}/></button></div></section>
   <section className="px-5 py-20 lg:px-8 lg:py-24"><div className="mx-auto max-w-4xl"><p className="text-sm font-extrabold uppercase tracking-[.18em] text-primary">Perguntas frequentes</p><h2 className="mt-3 text-3xl font-extrabold sm:text-5xl">Perguntas frequentes sobre o Marcenapp.</h2><div className="mt-10 divide-y divide-border border-y border-border">{faqs.map(([q,a],i)=><div key={q}><button onClick={()=>setFaq(faq===i?null:i)} className="flex w-full items-center justify-between gap-4 py-5 text-left font-extrabold">{q}<ChevronDown className={`shrink-0 transition-transform ${faq===i?'rotate-180':''}`}/></button>{faq===i&&<p className="pb-5 pr-8 leading-7 text-muted-foreground">{a}</p>}</div>)}</div></div></section>
   <section className="bg-slate-950 px-5 py-20 text-center text-white lg:px-8 lg:py-24"><h2 className="text-3xl font-extrabold sm:text-5xl">Seu próximo projeto pode começar aqui.</h2><p className="mx-auto mt-5 max-w-2xl text-lg text-slate-300">Organize o projeto, desenvolva o móvel e reúna as informações necessárias para seguir para a produção.</p><button onClick={go} className="mt-8 rounded-2xl bg-primary px-8 py-4 font-extrabold text-white">Começar agora <ArrowRight className="ml-2 inline" size={18}/></button></section>
  </main><footer className="border-t border-border px-5 py-8"><div className="mx-auto flex max-w-7xl flex-col gap-3 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between"><span className="font-extrabold text-foreground">MARCENAPP</span><span>Do projeto à produção, tudo no lugar.</span></div></footer>
 </div>;
}
