import React, { useEffect, useState } from 'react';
import { ArrowLeft, ExternalLink, Link2, MapPin, MessageCircle } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client';

type Profile = { name:string; company:string; trade_name:string; bio:string; phone:string; city:string; state:string; website_url:string; instagram_url:string; facebook_url:string; whatsapp_url:string; other_links:{label:string;url:string}[]; specialties:string[]; avatar_url:string };
type ProfileRow = Partial<Profile> & { [key:string]: unknown };
type ProfileQuery = {
 select:(columns:string)=>ProfileQuery;
 eq:(column:string,value:unknown)=>ProfileQuery;
 maybeSingle:()=>Promise<{data:ProfileRow|null;error:unknown}>;
};
const profilesTable = () => (supabase.from as unknown as (table:string)=>ProfileQuery)('profiles');

export default function MarceneiroPublico(){
 const {slug}=useParams(); const navigate=useNavigate(); const [p,setP]=useState<Profile|null>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const {data}=await profilesTable().select('name,company,trade_name,bio,phone,city,state,website_url,instagram_url,facebook_url,whatsapp_url,other_links,specialties,avatar_url').eq('public_slug',slug).eq('is_public',true).maybeSingle();if(data)setP({name:String(data.name??''),company:String(data.company??''),trade_name:String(data.trade_name??''),bio:String(data.bio??''),phone:String(data.phone??''),city:String(data.city??''),state:String(data.state??''),website_url:String(data.website_url??''),instagram_url:String(data.instagram_url??''),facebook_url:String(data.facebook_url??''),whatsapp_url:String(data.whatsapp_url??''),other_links:Array.isArray(data.other_links)?data.other_links.filter((item): item is {label:string;url:string} => Boolean(item&&typeof item==='object'&&typeof (item as Record<string,unknown>).label==='string'&&typeof (item as Record<string,unknown>).url==='string')):[],specialties:Array.isArray(data.specialties)?data.specialties.filter((item):item is string=>typeof item==='string'):[],avatar_url:String(data.avatar_url??'')});setLoading(false);})();},[slug]);
 if(loading)return <div className="min-h-screen bg-slate-50 flex items-center justify-center"><div className="w-80 h-56 bg-white rounded-3xl animate-pulse"/></div>;
 if(!p)return <div className="min-h-screen bg-slate-50 flex items-center justify-center p-6"><div className="bg-white rounded-3xl p-8 text-center max-w-md"><h1 className="text-xl font-black">Perfil não encontrado</h1><p className="text-slate-500 mt-2">Essa vitrine pode estar desativada ou o endereço mudou.</p><button onClick={()=>navigate('/')} className="mt-5 rounded-xl bg-slate-900 text-white px-5 py-2.5 font-bold">Ir para MARCENAPP</button></div></div>;
 const links=[['Site',p.website_url],['Instagram',p.instagram_url],['Facebook',p.facebook_url],['WhatsApp',p.whatsapp_url]].filter(([,url]): url is string=>Boolean(url));
 return <main className="min-h-screen bg-slate-50"><div className="max-w-3xl mx-auto px-4 py-8 md:py-12"><button onClick={()=>navigate('/')} className="text-sm font-bold text-slate-500 hover:text-slate-900 flex items-center gap-2"><ArrowLeft size={16}/> MARCENAPP</button><section className="mt-6 bg-white rounded-[2rem] border border-slate-200 overflow-hidden shadow-sm"><div className="h-28 bg-slate-900"/><div className="px-6 md:px-8 pb-8"><div className="-mt-12 flex items-end justify-between gap-4"><div className="w-24 h-24 rounded-3xl bg-indigo-600 text-white border-4 border-white flex items-center justify-center text-3xl font-black shadow-lg overflow-hidden">{p.avatar_url?<img src={p.avatar_url} className="w-full h-full object-cover"/>:(p.company||p.name||'M').charAt(0).toUpperCase()}</div>{p.whatsapp_url&&<a href={p.whatsapp_url} target="_blank" rel="noreferrer" className="rounded-xl bg-indigo-600 text-white px-4 py-2.5 font-bold flex items-center gap-2"><MessageCircle size={17}/> Falar</a>}</div><h1 className="text-2xl md:text-3xl font-black mt-4">{p.trade_name||p.company||p.name}</h1>{p.company&&p.trade_name&&<p className="text-slate-500 font-semibold">{p.company}</p>}{(p.city||p.state)&&<p className="text-sm text-slate-500 mt-2 flex items-center gap-1"><MapPin size={15}/>{[p.city,p.state].filter(Boolean).join(' · ')}</p>}{p.bio&&<p className="mt-5 text-slate-700 leading-relaxed whitespace-pre-wrap">{p.bio}</p>}<div className="flex flex-wrap gap-2 mt-5">{(p.specialties||[]).map(s=><span key={s} className="rounded-full bg-indigo-50 text-indigo-700 px-3 py-1.5 text-xs font-bold">{s}</span>)}</div><div className="grid sm:grid-cols-2 gap-3 mt-7">{links.map(([label,url])=><a key={label} href={url} target="_blank" rel="noreferrer" className="rounded-2xl border border-slate-200 p-4 flex items-center justify-between hover:bg-slate-50"><span className="font-bold">{label}</span><ExternalLink size={16} className="text-slate-400"/></a>)}{(p.other_links||[]).map(l=><a key={l.url} href={l.url} target="_blank" rel="noreferrer" className="rounded-2xl border border-slate-200 p-4 flex items-center justify-between hover:bg-slate-50"><span className="font-bold flex items-center gap-2"><Link2 size={16} className="text-indigo-600"/>{l.label}</span><ExternalLink size={16} className="text-slate-400"/></a>)}</div></div></section><p className="text-center text-xs text-slate-400 mt-5">Perfil profissional compartilhado pelo MARCENAPP</p></div></main>;
}
