import React from 'react';
import { Maximize2, Loader2, AlertCircle, RefreshCcw, ExternalLink, CheckCircle2, CircleAlert, FileText, Sparkles } from 'lucide-react';

export interface ChatMessage { id: string; user_id: string; project_id?: string | null; sender: string; text: string | null; image_url: string | null; budget: string | null; created_at: string; metadata?: { commandId?: string; resultUrl?: string; domain?: string; action?: string; agent?: string; correlationId?: string; status?: 'requested' | 'processing' | 'ready' | 'needs_input' | 'completed' | 'failed' | 'error'; intent?: { domain: string; action: string; agent: string }; artifact?: { type: string; id?: string }; artifacts?: Array<{ type: string; id?: string }>; panel?: { type: string }; actions?: Array<{ id: string; label: string; kind: string }> } | null; }
const SUGGESTIONS = ['Quero começar este projeto', 'Analisar este ambiente', 'Conferir medidas', 'Gerar um render'];
const ARTIFACT_LABELS: Record<string, string> = { project: 'Projeto', render: 'Render', budget: 'Orçamento', cut_plan: 'Plano de corte', materials: 'Materiais', hardware: 'Ferragens', contract: 'Documento', order: 'Pedido', checklist: 'Checklist', production: 'Produção' };
const STATUS_LABELS: Record<string, string> = { requested: 'Solicitado', processing: 'Preparando', ready: 'Pronto', completed: 'Concluído', needs_input: 'Aguardando informação', failed: 'Não concluído', error: 'Precisa de atenção' };
interface ChatMessagesProps { messages: ChatMessage[]; isTyping: boolean; onImageZoom: (data: { url: string; budget?: string | null }) => void; onArtifactOpen?: (data: { type: string; id?: string; imageUrl?: string | null }) => void; messagesEndRef: React.RefObject<HTMLDivElement>; error?: string | null; onRetry?: () => void; onDismissError?: () => void; onSuggestion?: (text: string) => void; }

export const ChatMessages = ({ messages, isTyping, onImageZoom, onArtifactOpen, messagesEndRef, error, onRetry, onDismissError, onSuggestion }: ChatMessagesProps) => (
  <main className="flex-1 overflow-y-auto px-3 py-5 sm:px-6 sm:py-7 scrollbar-thin relative" aria-live="polite">
    {messages.length === 0 && !isTyping && <div className="mx-auto flex min-h-[52vh] max-w-2xl flex-col items-center justify-center px-4 text-center"><div className="mb-4 flex h-11 w-11 items-center justify-center rounded-xl bg-primary/10 text-primary"><Sparkles size={20} aria-hidden="true" /></div><p className="text-lg font-semibold tracking-tight text-foreground">Vamos começar este projeto.</p><p className="mt-2 max-w-lg text-sm leading-6 text-muted-foreground">Conte à IARA o que você precisa fazer. Você pode escrever, enviar uma foto ou falar — a conversa acompanha o projeto.</p>{onSuggestion && <div className="mt-6 flex max-w-xl flex-wrap justify-center gap-2">{SUGGESTIONS.map(s => <button key={s} type="button" onClick={() => onSuggestion(s)} className="min-h-9 rounded-full border border-border bg-background px-3.5 py-2 text-xs text-foreground transition-colors hover:border-primary/50 hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/40">{s}</button>)}</div>}</div>}
    {messages.map((msg) => { const isUser = msg.sender === 'user'; const artifact = msg.metadata?.artifact; const status = msg.metadata?.status; const canOpenArtifact = Boolean(artifact && onArtifactOpen); const statusIcon = status === 'ready' || status === 'completed' ? <CheckCircle2 size={13} aria-hidden="true" /> : status === 'failed' || status === 'error' ? <CircleAlert size={13} aria-hidden="true" /> : <Loader2 size={13} className={status === 'processing' ? 'animate-spin' : ''} aria-hidden="true" />; return <div key={msg.id} className={`mx-auto flex w-full max-w-4xl flex-col ${isUser ? 'items-end' : 'items-start'}`}><div className={`max-w-[94%] sm:max-w-[78%] rounded-2xl ${isUser ? 'bg-primary rounded-tr-sm' : 'bg-card border border-border/70 rounded-tl-sm'}`}>{msg.image_url && <div className="relative m-1 cursor-zoom-in overflow-hidden rounded-xl" onClick={() => isUser && onImageZoom({ url: msg.image_url!, budget: msg.budget })}><img src={msg.image_url} className="max-h-[420px] w-full object-cover" alt="Referência enviada" /><div className="absolute right-2 top-2"><span className="rounded-full bg-black/40 px-2 py-0.5 text-[8px] font-bold uppercase tracking-widest text-white backdrop-blur-sm">Imagem</span></div></div>}{msg.text && <div className={`whitespace-pre-wrap px-4 py-3 text-sm leading-6 ${isUser ? 'text-primary-foreground' : 'text-foreground'}`}>{msg.text}</div>}{artifact && <div className={`mx-3 mb-3 rounded-xl border p-3 ${isUser ? 'border-primary-foreground/25 bg-primary-foreground/5' : 'border-border bg-muted/30'}`}><div className="flex items-start gap-2"><div className="mt-0.5 rounded-lg border border-border bg-background p-1.5"><FileText size={14} aria-hidden="true" /></div><div className="min-w-0 flex-1"><p className="text-xs font-semibold">{ARTIFACT_LABELS[artifact.type] ?? 'Artefato do projeto'}</p>{status && <div className="mt-1 flex items-center gap-1.5 text-[10px] text-muted-foreground" aria-label={STATUS_LABELS[status] ?? status}>{statusIcon}<span>{STATUS_LABELS[status] ?? status}</span></div>}</div></div>{canOpenArtifact && <button type="button" onClick={() => onArtifactOpen?.({ type: artifact.type, id: artifact.id, imageUrl: msg.image_url })} className={`mt-3 inline-flex min-h-10 w-full items-center justify-center gap-2 rounded-lg border px-3 py-2 text-xs font-semibold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary ${isUser ? 'border-primary-foreground/30 text-primary-foreground hover:bg-primary-foreground/10' : 'border-border text-foreground hover:bg-background'}`}><ExternalLink size={14} /> {artifact.type === 'render' ? 'Abrir render' : 'Ver detalhes'}</button>}</div>}<div className={`px-3 pb-2 text-[9px] font-medium text-right ${isUser ? 'text-primary-foreground/60' : 'text-muted-foreground'}`}>{new Date(msg.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</div></div></div>; })}
    {error && !isTyping && <div role="alert" className="mx-auto flex max-w-2xl items-start gap-3 rounded-xl border border-destructive/20 bg-destructive/5 p-3 animate-in fade-in"><AlertCircle size={16} className="mt-0.5 shrink-0 text-destructive" aria-hidden="true" /><div className="min-w-0 flex-1"><p className="text-xs font-semibold text-foreground">Não foi possível continuar</p><p className="mt-1 break-words text-[11px] leading-relaxed text-muted-foreground">{error}</p><div className="mt-2 flex gap-2">{onRetry && <button type="button" onClick={onRetry} className="inline-flex min-h-9 items-center gap-1 rounded-lg bg-primary px-3 py-1.5 text-[10px] font-semibold text-primary-foreground hover:opacity-90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"><RefreshCcw size={12} aria-hidden="true" /> Tentar novamente</button>}{onDismissError && <button type="button" onClick={onDismissError} className="min-h-9 px-3 py-1.5 text-[10px] font-medium text-muted-foreground hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary">Fechar</button>}</div></div></div>}
    {isTyping && <div className="mx-auto flex w-full max-w-4xl items-start"><div role="status" aria-live="polite" className="flex items-center gap-2 rounded-2xl rounded-tl-sm border border-border/70 bg-card p-3"><Loader2 size={16} className="animate-spin text-primary" aria-hidden="true" /><span className="text-xs text-muted-foreground">IARA está preparando...</span></div></div>}
    <div ref={messagesEndRef} />
  </main>
);
