// IARA OS v1 — Tool Registry (client-side executors)
// Contracts are stable. AI selects a tool; this registry executes inside the same RLS/trust boundaries.
import { z } from 'zod';
import type { SupabaseClient } from '@supabase/supabase-js';
import { supabase } from '@/integrations/supabase/client';
import { useStudioStore } from '@/store/useStudioStore';
import { useMarcenappOS } from '@/store/useMarcenappOS';
import { callAIContractClause } from '@/services/ai';

const db = supabase as unknown as SupabaseClient;
export type ToolResult<T = unknown> = | { ok: true; data: T } | { ok: false; error: string };
export interface ToolDefinition<TArgs extends object, TResult = unknown> { name: string; description: string; version: string; inputSchema: z.ZodTypeAny; execute: (args: TArgs, ctx: ExecutionContext) => Promise<ToolResult<TResult>>; }
export interface ExecutionContext { userId: string; projectId?: string; environmentId?: string; versionId?: string; correlationId?: string; generation?: number; decorStyle?: string; lastImageBase?: string; lastImageMask?: string; }

type CreateClienteArgs = { nome: string; email?: string; telefone?: string };
type CreateProjetoArgs = { nome: string; clienteNome?: string; width: number; height: number; depth: number; tipo?: string; confirmado: true };
type GerarRenderArgs = { prompt: string; estilo?: string };
type CalcularOrcamentoArgs = { projetoId?: string };
type OperationalArgs = { projetoId?: string };
type GerarContratoArgs = { clienteNome: string; valor?: number; prazoDias?: number; clausulasExtras?: string[] };
type ClienteData = { id: string; nome: string };
type ProjetoData = { id: string; nome: string; width: number; height: number; depth: number };
type RenderData = { studioCommandId?: string; status: string; imageUrl?: string };
type OrcamentoData = { projetoId: string; nome: string; total: number; materiais: number; ferragens: number; maoDeObra: number; outros: number; precoVenda: number; lucro: number; margemPct: number; isEstimate: false };
type OperationalData = { projetoId: string; alertas: unknown[]; dados: Record<string, unknown> };
type ContratoData = { cliente: string; valor: number | null; prazoDias: number | null; clausulasGeradas: number; clausulas: string[] };

const createCliente: ToolDefinition<CreateClienteArgs, ClienteData> = { name: 'createCliente', description: 'Cria um novo cliente no tenant atual', version: '1.0.0', inputSchema: z.object({ nome: z.string().min(1), email: z.string().email().optional().or(z.literal('')), telefone: z.string().optional() }), async execute(args, ctx) { const { data, error } = await db.from('clientes').insert({ user_id: ctx.userId, nome: args.nome, email: args.email || null, telefone: args.telefone || null }).select('id, nome').single(); if (error) return { ok: false, error: error.message }; return { ok: true, data: data as ClienteData }; } };
const createProjeto: ToolDefinition<CreateProjetoArgs, ProjetoData> = { name: 'createProjeto', description: 'Cria projeto somente após confirmação explícita das três dimensões', version: '1.1.0', inputSchema: z.object({ nome: z.string().min(1), clienteNome: z.string().optional(), width: z.number().positive(), height: z.number().positive(), depth: z.number().positive(), tipo: z.string().optional(), confirmado: z.literal(true) }), async execute(args, ctx) { let clienteId: string | null = null; if (args.clienteNome) { const { data: cli } = await db.from('clientes').select('id').eq('user_id', ctx.userId).ilike('nome', args.clienteNome).maybeSingle(); clienteId = (cli as { id: string } | null)?.id ?? null; } const { data, error } = await db.from('projects').insert({ user_id: ctx.userId, nome: args.nome, cliente_id: clienteId, width: args.width, height: args.height, depth: args.depth }).select('id, nome, width, height, depth').single(); if (error) return { ok: false, error: error.message }; return { ok: true, data: data as ProjetoData }; } };
const gerarRender: ToolDefinition<GerarRenderArgs, RenderData> = { name: 'gerarRender', description: 'Gera visual no Estúdio. Aceita texto sozinho; com imagem base, usa a imagem enviada mesmo sem máscara; com máscara, preserva o fluxo contextual do ambiente.', version: '1.4.0', inputSchema: z.object({ prompt: z.string().min(1), estilo: z.string().optional() }), async execute(args, ctx) { const estilo = args.estilo || ctx.decorStyle || 'Limpo'; const idempotencyKey = ctx.correlationId; const images = ctx.lastImageBase ? [{ mimeType: 'image/jpeg', data: ctx.lastImageBase }, ...(ctx.lastImageMask ? [{ mimeType: 'image/png', data: ctx.lastImageMask }] : [])] : undefined; const id = useStudioStore.getState().enqueueCommand({ prompt: `MARCENAPP IARA OS: móvel estilo ${estilo}. ${args.prompt}`, images, decor: estilo, idempotencyKey, metadata: { origin: 'iara', originalPrompt: args.prompt, targetModule: 'studio' } }); useMarcenappOS.getState().dispatchCommand({ source: 'iara', target: 'studio', action: 'GENERATE_VISUAL', payload: { prompt: args.prompt, estilo, studioCommandId: id, userId: ctx.userId, ...(ctx.projectId ? { projectId: ctx.projectId } : {}), ...(ctx.environmentId ? { environmentId: ctx.environmentId } : {}), ...(ctx.versionId ? { versionId: ctx.versionId } : {}), ...(ctx.correlationId ? { correlationId: ctx.correlationId } : {}), ...(typeof ctx.generation === 'number' ? { generation: ctx.generation } : {}) } }); return { ok: true, data: { studioCommandId: id, status: 'queued' } }; } };
const calcularOrcamento: ToolDefinition<CalcularOrcamentoArgs, OrcamentoData> = { name: 'calcularOrcamento', description: 'Consulta um orçamento real salvo para o projeto; nunca inventa preço de MDF, ferragens ou mão de obra', version: '3.0.0', inputSchema: z.object({ projetoId: z.string().uuid().optional() }), async execute(args, ctx) { const projectId = args.projetoId || ctx.projectId; const query = db.from('project_cost_snapshots').select('project_id,sale_price,material_cost,hardware_cost,labor_cost,other_cost').eq('user_id', ctx.userId); const { data: row, error } = projectId ? await query.eq('project_id', projectId).maybeSingle() : await query.order('updated_at', { ascending: false }).limit(1).maybeSingle(); if (error) return { ok: false, error: error.message }; if (!row) return { ok: false, error: 'Não há orçamento real salvo para este projeto. Informe os custos reais e o preço de venda no módulo Orçamento.' }; const r = row as { project_id: string; sale_price: number | null; material_cost: number | null; hardware_cost: number | null; labor_cost: number | null; other_cost: number | null }; const missing = [r.material_cost == null ? 'materiais' : null, r.hardware_cost == null ? 'ferragens' : null, r.labor_cost == null ? 'mão de obra' : null, r.sale_price == null ? 'preço de venda' : null].filter(Boolean); if (missing.length) return { ok: false, error: `Dados insuficientes para orçamento real: faltam ${missing.join(', ')}.` }; const { data: project } = await db.from('projects').select('id,nome,name').eq('user_id', ctx.userId).eq('id', r.project_id).maybeSingle(); const materiais = Number((r.material_cost ?? 0).toFixed(2)); const ferragens = Number((r.hardware_cost ?? 0).toFixed(2)); const maoDeObra = Number((r.labor_cost ?? 0).toFixed(2)); const outros = Number((r.other_cost ?? 0).toFixed(2)); const precoVenda = Number((r.sale_price ?? 0).toFixed(2)); const custoTotal = Number((materiais + ferragens + maoDeObra + outros).toFixed(2)); const lucro = Number((precoVenda - custoTotal).toFixed(2)); const margemPct = precoVenda > 0 ? Number(((lucro / precoVenda) * 100).toFixed(2)) : 0; const projectRow = project as { nome?: string | null; name?: string | null } | null; return { ok: true, data: { projetoId: r.project_id, nome: projectRow?.nome || projectRow?.name || 'Projeto', total: precoVenda, materiais, ferragens, maoDeObra, outros, precoVenda, lucro, margemPct, isEstimate: false } }; } };
const operationalIntelligence: ToolDefinition<OperationalArgs, OperationalData> = { name: 'operationalIntelligence', description: 'Analisa um projeto com custos, ferragens, estoque, produção, venda, recebimentos e regras reais; nunca preenche lacunas com números', version: '2.0.0', inputSchema: z.object({ projetoId: z.string().uuid().optional() }), async execute(args, ctx) { let projectId = args.projetoId || ctx.projectId; if (!projectId) { const { data: p } = await db.from('projects').select('id').eq('user_id', ctx.userId).order('updated_at', { ascending: false }).limit(1).maybeSingle(); projectId = (p as { id: string } | null)?.id; } if (!projectId) return { ok: false, error: 'Nenhum projeto encontrado.' }; const { error } = await db.rpc('refresh_project_operational_alerts', { p_project_id: projectId }); if (error) return { ok: false, error: error.message }; const [{ data: project }, { data: alerts }, { data: requirements }, { data: stages }, { data: sale }, { data: receivables }] = await Promise.all([db.from('projects').select('id,nome,name,doors,drawers,modules').eq('user_id',ctx.userId).eq('id',projectId).maybeSingle(), db.from('operational_alerts').select('alert_type,severity,message,evidence,suggested_action').eq('user_id',ctx.userId).eq('entity_id',projectId).eq('status','open').order('created_at',{ascending:false}), db.from('project_hardware_requirements').select('hardware_id,quantity_required,rule_key').eq('user_id',ctx.userId).eq('project_id',projectId), db.from('project_production_stages').select('stage_key,stage_name,status,responsible,due_at,blocked_reason').eq('user_id',ctx.userId).eq('project_id',projectId), db.from('project_sales').select('sale_price,status').eq('user_id',ctx.userId).eq('project_id',projectId).maybeSingle(), db.from('project_receivables').select('installment_number,amount,due_at,received_at,status').eq('user_id',ctx.userId).eq('project_id',projectId)]); return { ok: true, data: { projetoId: projectId, alertas: alerts ?? [], dados: { projeto: project, ferragens: requirements ?? [], producao: stages ?? [], venda: sale, recebimentos: receivables ?? [] } } }; } };
const gerarContrato: ToolDefinition<GerarContratoArgs, ContratoData> = { name: 'gerarContrato', description: 'Gera documentação contratual assistida por IA; não constitui aconselhamento jurídico', version: '1.4.0', inputSchema: z.object({ clienteNome: z.string().min(1), valor: z.number().optional(), prazoDias: z.number().optional(), clausulasExtras: z.array(z.string()).optional() }), async execute(args) { const clausulas: string[] = []; for (const desc of args.clausulasExtras ?? []) { try { const result = await callAIContractClause(desc); if (!result.text) return { ok: false, error: `A IA não retornou uma cláusula para: ${desc}` }; clausulas.push(result.text); } catch (e) { return { ok: false, error: `Falha ao gerar cláusula "${desc}": ${e instanceof Error ? e.message : 'erro desconhecido'}` }; } } return { ok: true, data: { cliente: args.clienteNome, valor: args.valor ?? null, prazoDias: args.prazoDias ?? null, clausulasGeradas: clausulas.length, clausulas } }; } };
const TOOLS = { createCliente, createProjeto, gerarRender, calcularOrcamento, operationalIntelligence, gerarContrato };
type ToolName = keyof typeof TOOLS;
type ErasedTool = { inputSchema: z.ZodTypeAny; execute: (args: Record<string, unknown>, ctx: ExecutionContext) => Promise<ToolResult<unknown>> };
export function getTool(name: string): ToolDefinition<object, unknown> | undefined { return TOOLS[name as ToolName] as unknown as ToolDefinition<object, unknown> | undefined; }
export function listTools(): ToolDefinition<object, unknown>[] { return Object.values(TOOLS) as unknown as ToolDefinition<object, unknown>[]; }
export async function executeToolCall(name: string, args: unknown, ctx: ExecutionContext): Promise<ToolResult<unknown>> { const tool = getTool(name); if (!tool) return { ok: false, error: `Ferramenta desconhecida: ${name}` }; const parsed = tool.inputSchema.safeParse(args); if (!parsed.success) return { ok: false, error: `Argumentos inválidos para ${name}: ${JSON.stringify(parsed.error.flatten().fieldErrors)}` }; try { return await (tool as unknown as ErasedTool).execute(parsed.data as Record<string, unknown>, ctx); } catch (e) { return { ok: false, error: e instanceof Error ? e.message : 'Erro desconhecido' }; }
}
