import React, { useState, useRef, useEffect } from 'react';
import { X, ChevronDown, ArrowLeft } from 'lucide-react';
import { ChatMessages } from './components/ChatMessages';
import { ChatInput, type SmartAction } from './components/ChatInput';
import { ContextPanel, type ContextPanelData } from './components/ContextPanel';
import AuthDialog from '../../components/marcenaria/AuthDialog';
import { useIaraChat } from './hooks/useIaraChat';
import type { IaraContext } from './services/iaraContext';

interface IaraModuleProps { syncProject?: { width?: number; height?: number; depth?: number } | null; onProjectChange?: (p: { width: number; height: number; depth: number }) => void; embedded?: boolean; projectId?: string | null; activeContext?: IaraContext; navigateTo?: (id: string, params?: Record<string, string>) => void; environments?: Array<{ id: string; name: string; position: number }>; versions?: Array<{ id: string; version_number: number; environment_id: string }>; onEnvironmentChange?: (id: string) => void; onVersionChange?: (id: string) => void; }

type UploadKind = 'environment' | 'reference' | 'sketch' | 'plan';
type PendingUpload = { base64: string; baseRaw?: string; maskRaw?: string; kind?: UploadKind };

const IaraModule = ({ syncProject, onProjectChange, embedded, projectId = null, activeContext, environments = [], versions = [], onEnvironmentChange, onVersionChange, navigateTo }: IaraModuleProps = {}) => {
  const [showAuthDialog, setShowAuthDialog] = useState(false);
  const [contextPanel, setContextPanel] = useState<ContextPanelData | null>(null);
  const [factors, setFactors] = useState({ L: syncProject?.width ?? 2.4, A: syncProject?.height ?? 2.6, P: syncProject?.depth ?? 0.6, E: 0.018, X: 0, Y: 0 });
  const [decorStyle] = useState('Limpo');
  const [activeImageZoom, setActiveImageZoom] = useState<{ url: string; budget?: string | null } | null>(null);
  useEffect(() => { if (!syncProject) return; setFactors(prev => { const next = { ...prev, L: syncProject.width ?? prev.L, A: syncProject.height ?? prev.A, P: syncProject.depth ?? prev.P }; if (next.L === prev.L && next.A === prev.A && next.P === prev.P) return prev; return next; }); }, [syncProject, syncProject?.width, syncProject?.height, syncProject?.depth]);
  useEffect(() => { if (!onProjectChange) return; const sameAsStudio = syncProject?.width === factors.L && syncProject?.height === factors.A && syncProject?.depth === factors.P; if (sameAsStudio) return; onProjectChange({ width: factors.L, height: factors.A, depth: factors.P }); }, [factors.L, factors.A, factors.P, onProjectChange, syncProject?.width, syncProject?.height, syncProject?.depth]);
  const { messages, hasOlderMessages, isLoadingOlderMessages, loadOlderMessages, chatInput, setChatInput, isTyping, isListening, handleSend, handleSmartAction, handleImageSelect, toggleRecording, maskingImage, setMaskingImage, pendingUpload, setPendingUpload, error, retryLast, dismissError } = useIaraChat(factors, decorStyle, setShowAuthDialog, { onProjectCreated: (p) => setFactors(prev => ({ ...prev, L: p.width ?? prev.L, A: p.height ?? prev.A, P: p.depth ?? prev.P })) }, projectId, activeContext);
  const lastPushedRef = useRef<string | null>(null); const isDrawingRef = useRef(false); const messagesEndRef = useRef<HTMLDivElement>(null); const canvasRef = useRef<HTMLCanvasElement>(null); const ctxRef = useRef<CanvasRenderingContext2D | null>(null); const lastMessageIdRef = useRef<string | null>(null);
  void lastPushedRef;
  useEffect(() => { const lastMessageId = messages[messages.length - 1]?.id ?? null; if (lastMessageId && lastMessageId !== lastMessageIdRef.current) messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' }); lastMessageIdRef.current = lastMessageId; }, [messages, isTyping]);
  useEffect(() => { if (maskingImage && canvasRef.current) { const c = canvasRef.current; c.width = 1080; c.height = 1920; const ctx = c.getContext('2d'); if (ctx) { ctx.lineCap = 'round'; ctx.lineJoin = 'round'; ctx.strokeStyle = 'rgba(255, 255, 255, 0.85)'; ctx.lineWidth = 60; ctxRef.current = ctx; } } }, [maskingImage]);
  type CanvasPointerEvent = React.MouseEvent<HTMLCanvasElement> | React.TouchEvent<HTMLCanvasElement>;
  const getCoords = (e: CanvasPointerEvent) => { const rect = canvasRef.current?.getBoundingClientRect(); if (!rect) return null; const sx = 1080 / rect.width; const sy = 1920 / rect.height; const point = 'touches' in e ? e.touches[0] : e; if (!point) return null; return { offsetX: (point.clientX - rect.left) * sx, offsetY: (point.clientY - rect.top) * sy }; };
  const startDraw = (e: CanvasPointerEvent) => { if (!ctxRef.current) return; const c = getCoords(e); if (!c) return; ctxRef.current.beginPath(); ctxRef.current.moveTo(c.offsetX, c.offsetY); isDrawingRef.current = true; };
  const moveDraw = (e: CanvasPointerEvent) => { if (!isDrawingRef.current || !ctxRef.current) return; const c = getCoords(e); if (!c) return; ctxRef.current.lineTo(c.offsetX, c.offsetY); ctxRef.current.stroke(); };
  const endDraw = () => { isDrawingRef.current = false; };
  const confirmMask = async () => { if (!maskingImage || !canvasRef.current) return; const canvas = document.createElement('canvas'); canvas.width = 1080; canvas.height = 1920; const ctx = canvas.getContext('2d'); if (!ctx) return; ctx.fillStyle = '#000000'; ctx.fillRect(0, 0, 1080, 1920); const ratio = Math.min(1080 / maskingImage.img.width, 1920 / maskingImage.img.height); const dw = maskingImage.img.width * ratio; const dh = maskingImage.img.height * ratio; ctx.drawImage(maskingImage.img, (1080 - dw) / 2, (1920 - dh) / 2, dw, dh); const baseB64 = canvas.toDataURL('image/jpeg', 0.7); const baseRaw = baseB64.split(',')[1]; ctx.clearRect(0, 0, 1080, 1920); ctx.fillStyle = '#000000'; ctx.fillRect(0, 0, 1080, 1920); ctx.drawImage(canvasRef.current, 0, 0); const idata = ctx.getImageData(0, 0, 1080, 1920); const d = idata.data; for (let i = 0; i < d.length; i += 4) { if (d[i + 3] > 10) { d[i] = d[i + 1] = d[i + 2] = 255; d[i + 3] = 255; } else { d[i] = d[i + 1] = d[i + 2] = 0; d[i + 3] = 255; } } ctx.putImageData(idata, 0, 0); const maskRaw = canvas.toDataURL('image/png').split(',')[1]; setPendingUpload({ base64: baseB64, baseRaw, maskRaw, kind: maskingImage.kind }); setMaskingImage(null); };
  const openArtifact = (data: { type: string; id?: string; imageUrl?: string | null }) => setContextPanel({ title: data.type === 'render' ? 'Render do projeto' : data.type === 'budget' ? 'Orçamento do projeto' : 'Artefato do projeto', type: data.type, imageUrl: data.imageUrl, description: projectId ? 'Este contexto está vinculado ao trabalho atual e permanece disponível sem sair da conversa.' : undefined });
  const onSmartAction = (action: SmartAction) => void handleSmartAction(action);
  const updatePendingUpload = (value: PendingUpload | null) => setPendingUpload(value ? { base64: value.base64, baseRaw: value.baseRaw ?? '', maskRaw: value.maskRaw ?? '', kind: value.kind ?? 'environment' } : null);
  return (<div className={`flex min-h-0 flex-col ${embedded ? 'h-full' : 'h-[calc(100vh-8rem)] md:h-[calc(100vh-4rem)]'} bg-background relative overflow-hidden rounded-xl border border-border`}>
    <header className="px-3 py-2 bg-card border-b border-border shrink-0">
      {projectId ? <div className="flex min-w-0 flex-wrap items-center gap-1.5 text-[10px]">
        <span className="rounded-full bg-muted px-2.5 py-1 font-semibold text-foreground">Cliente: {activeContext?.clientName ?? '—'}</span>
        <span className="rounded-full bg-muted px-2.5 py-1 font-semibold text-foreground">Projeto: {activeContext?.projectName ?? '—'}</span>
        <label className="relative inline-flex items-center rounded-full border border-border bg-background pl-2.5 pr-1 py-1 font-semibold"><span>Ambiente: {activeContext?.environmentName ?? '—'}</span>{environments.length > 0 && <><ChevronDown size={12} className="ml-1" /><select aria-label="Ambiente ativo" value={activeContext?.environmentId ?? ''} onChange={e => onEnvironmentChange?.(e.target.value)} className="absolute inset-0 opacity-0 cursor-pointer">{environments.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></>}</label>
        <label className="relative inline-flex items-center rounded-full border border-border bg-background pl-2.5 pr-1 py-1 font-semibold"><span>Versão: {activeContext?.versionNumber != null ? `v${activeContext.versionNumber}` : '—'}</span>{versions.length > 0 && <><ChevronDown size={12} className="ml-1" /><select aria-label="Versão ativa" value={activeContext?.versionId ?? ''} onChange={e => onVersionChange?.(e.target.value)} className="absolute inset-0 opacity-0 cursor-pointer">{versions.map(item => <option key={item.id} value={item.id}>v{item.version_number}</option>)}</select></>}</label>
        <span className="ml-auto rounded-full border border-border px-2.5 py-1 font-medium text-muted-foreground">Contexto ativo</span>
      </div> : null}
    </header>
    {projectId ? <ChatMessages messages={messages} hasOlderMessages={hasOlderMessages} isLoadingOlderMessages={isLoadingOlderMessages} onLoadOlderMessages={loadOlderMessages} isTyping={isTyping} onImageZoom={setActiveImageZoom} onArtifactOpen={openArtifact} messagesEndRef={messagesEndRef} error={error} onRetry={retryLast} onDismissError={dismissError} /> : <main className="flex flex-1 items-center justify-center px-5 py-6 sm:px-8" aria-label="IARA sem projeto aberto"><div className="w-full max-w-md text-center"><p className="text-sm font-semibold text-foreground">A IARA está pronta.</p><p className="mt-1 text-xs text-muted-foreground">Você pode tirar uma foto do ambiente agora e escolher depois onde cadastrar.</p><button type="button" onClick={() => navigateTo?.('diario')} className="mt-3 inline-flex items-center gap-2 rounded-xl border border-border bg-card px-3 py-2 text-xs font-semibold text-foreground hover:bg-muted"><ArrowLeft size={14} aria-hidden="true" /> Clientes e Projetos</button></div></main>}
    <ChatInput chatInput={chatInput} setChatInput={setChatInput} onSend={handleSend} onImageSelect={handleImageSelect} toggleRecording={toggleRecording} isListening={isListening} pendingUpload={pendingUpload} setPendingUpload={updatePendingUpload} onSmartAction={onSmartAction} navigateTo={navigateTo} projectId={projectId} />
    {maskingImage && <div className="fixed inset-0 z-[300] bg-black/95 flex flex-col items-center justify-center p-4"><div className="w-full max-w-sm aspect-[9/16] relative bg-slate-900 rounded-3xl overflow-hidden shadow-2xl border border-white/10"><img src={maskingImage.src} className="absolute inset-0 w-full h-full object-contain pointer-events-none" alt="Imagem do ambiente" /><canvas ref={canvasRef} onMouseDown={startDraw} onMouseMove={moveDraw} onMouseUp={endDraw} onTouchStart={startDraw} onTouchMove={moveDraw} onTouchEnd={endDraw} className="absolute inset-0 w-full h-full touch-none cursor-crosshair" /><div className="absolute top-6 left-6 right-6 flex justify-between items-center bg-black/40 backdrop-blur-md p-4 rounded-2xl border border-white/5"><span className="text-white text-xs font-bold">Marque a área do móvel</span><button type="button" aria-label="Fechar marcação" onClick={() => setMaskingImage(null)} className="text-white/70 hover:text-white p-2"><X size={20}/></button></div></div><div className="mt-8 flex gap-4 w-full max-w-sm"><button type="button" onClick={() => setMaskingImage(null)} className="flex-1 py-4 bg-white/5 text-white/70 rounded-2xl font-bold text-xs">Cancelar</button><button type="button" onClick={confirmMask} className="flex-1 py-4 bg-primary text-white rounded-2xl font-bold text-xs">Confirmar marcação</button></div></div>}
    {activeImageZoom && <div className="fixed inset-0 z-[300] bg-black/95 flex items-center justify-center p-4" onClick={() => setActiveImageZoom(null)}><div className="relative max-w-4xl w-full" onClick={e => e.stopPropagation()}><img src={activeImageZoom.url} className="w-full h-auto rounded-2xl shadow-2xl" alt="Imagem ampliada" /><button type="button" onClick={() => setActiveImageZoom(null)} aria-label="Fechar imagem ampliada" className="absolute -top-4 -right-4 p-3 bg-white text-black rounded-full shadow-2xl"><X size={24}/></button>{activeImageZoom.budget && <div className="absolute bottom-6 left-6 bg-primary/90 backdrop-blur-lg px-6 py-3 rounded-2xl border border-white/20 shadow-2xl"><span className="text-white font-bold tracking-tight text-xl">R$ {activeImageZoom.budget}</span></div>}</div></div>}
    <ContextPanel panel={contextPanel} onClose={() => setContextPanel(null)} /><AuthDialog isOpen={showAuthDialog} onClose={() => setShowAuthDialog(false)} onSuccess={() => setShowAuthDialog(false)} />
  </div>);
};
export default IaraModule;
