-- IARA semantic memory foundation.
-- Supabase's built-in gte-small produces 384-dimensional embeddings.
create extension if not exists vector with schema extensions;

create table if not exists public.iara_memory_embeddings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  project_id uuid references public.projects(id) on delete cascade,
  message_id uuid references public.chat_messages(id) on delete cascade,
  source_type text not null default 'chat_message',
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  embedding extensions.vector(384) not null,
  created_at timestamptz not null default now()
);

create index if not exists iara_memory_embeddings_user_project_idx
  on public.iara_memory_embeddings(user_id, project_id, created_at desc);

create index if not exists iara_memory_embeddings_embedding_hnsw_idx
  on public.iara_memory_embeddings
  using hnsw (embedding vector_cosine_ops);

grant select on public.iara_memory_embeddings to authenticated;
grant all on public.iara_memory_embeddings to service_role;

alter table public.iara_memory_embeddings enable row level security;

drop policy if exists "Users can view own IARA memory" on public.iara_memory_embeddings;
create policy "Users can view own IARA memory"
  on public.iara_memory_embeddings
  for select to authenticated
  using ((select auth.uid()) = user_id);

create or replace function public.match_iara_memory(
  query_embedding extensions.vector(384),
  match_threshold float default 0.72,
  match_count int default 8,
  filter_project_id uuid default null
)
returns table (
  id uuid,
  project_id uuid,
  message_id uuid,
  source_type text,
  content text,
  metadata jsonb,
  similarity float
)
language sql
stable
security invoker
set search_path = public, extensions
as $$
  select
    m.id,
    m.project_id,
    m.message_id,
    m.source_type,
    m.content,
    m.metadata,
    1 - (m.embedding <=> query_embedding) as similarity
  from public.iara_memory_embeddings m
  where m.user_id = (select auth.uid())
    and (filter_project_id is null or m.project_id = filter_project_id)
    and m.embedding <=> query_embedding < 1 - match_threshold
  order by m.embedding <=> query_embedding asc
  limit least(greatest(match_count, 1), 50);
$$;

grant execute on function public.match_iara_memory(extensions.vector(384), float, int, uuid) to authenticated;
grant execute on function public.match_iara_memory(extensions.vector(384), float, int, uuid) to service_role;

comment on table public.iara_memory_embeddings is
  'Semantic memory for IARA. Embeddings are generated by the configured embedding provider and scoped to the owning user.';
