-- Operational Intelligence verticals 2-4: hardware, production, sales, receivables and project expenses.
-- All tables are tenant-scoped and protected by RLS.
create table if not exists public.hardware_suppliers (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, contact text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists idx_hardware_suppliers_user on public.hardware_suppliers(user_id);
create table if not exists public.hardware_items (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, category text not null, sku text, unit text not null default 'un', supplier_id uuid references public.hardware_suppliers(id) on delete set null, unit_price numeric check (unit_price is null or unit_price >= 0), minimum_stock numeric not null default 0 check (minimum_stock >= 0), active boolean not null default true, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists idx_hardware_items_user on public.hardware_items(user_id);
create table if not exists public.hardware_stock (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, hardware_id uuid not null references public.hardware_items(id) on delete cascade, quantity_on_hand numeric not null default 0 check (quantity_on_hand >= 0), updated_at timestamptz not null default now(), unique(user_id, hardware_id));
create index if not exists idx_hardware_stock_user on public.hardware_stock(user_id);
create table if not exists public.hardware_purchases (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, supplier_id uuid references public.hardware_suppliers(id) on delete set null, status text not null default 'draft' check (status in ('draft','ordered','received','cancelled')), ordered_at timestamptz, received_at timestamptz, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists idx_hardware_purchases_user on public.hardware_purchases(user_id);
create table if not exists public.hardware_purchase_items (id uuid primary key default gen_random_uuid(), purchase_id uuid not null references public.hardware_purchases(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, hardware_id uuid not null references public.hardware_items(id) on delete restrict, quantity numeric not null check (quantity > 0), unit_price numeric check (unit_price is null or unit_price >= 0), created_at timestamptz not null default now());
create index if not exists idx_hardware_purchase_items_user on public.hardware_purchase_items(user_id);
create table if not exists public.project_hardware_requirements (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, project_id uuid not null references public.projects(id) on delete cascade, hardware_id uuid not null references public.hardware_items(id) on delete cascade, quantity_required numeric not null check (quantity_required > 0), source text not null default 'rule', rule_key text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id, project_id, hardware_id));
create index if not exists idx_project_hardware_requirements_project on public.project_hardware_requirements(user_id, project_id);
create table if not exists public.project_production_stages (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, project_id uuid not null references public.projects(id) on delete cascade, stage_key text not null, stage_name text not null, status text not null default 'pending' check (status in ('pending','in_progress','blocked','completed','cancelled')), responsible text, started_at timestamptz, due_at timestamptz, completed_at timestamptz, blocked_reason text, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id, project_id, stage_key));
create index if not exists idx_project_production_project on public.project_production_stages(user_id, project_id);
create index if not exists idx_project_production_due on public.project_production_stages(user_id, due_at);
create table if not exists public.project_sales (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, project_id uuid not null references public.projects(id) on delete cascade, sale_price numeric not null check (sale_price > 0), sold_at timestamptz not null default now(), status text not null default 'sold' check (status in ('draft','sold','cancelled')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id, project_id));
create index if not exists idx_project_sales_user_project on public.project_sales(user_id, project_id);
create table if not exists public.project_receivables (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, project_id uuid not null references public.projects(id) on delete cascade, installment_number integer not null check (installment_number > 0), due_at timestamptz not null, amount numeric not null check (amount > 0), received_at timestamptz, status text not null default 'open' check (status in ('open','received','cancelled')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id, project_id, installment_number));
create index if not exists idx_project_receivables_user_due on public.project_receivables(user_id, due_at);
create table if not exists public.project_expenses (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, project_id uuid not null references public.projects(id) on delete cascade, description text not null, amount numeric not null check (amount >= 0), expense_date timestamptz not null default now(), category text, created_at timestamptz not null default now());
create index if not exists idx_project_expenses_project on public.project_expenses(user_id, project_id);

alter table public.hardware_suppliers enable row level security;
alter table public.hardware_items enable row level security;
alter table public.hardware_stock enable row level security;
alter table public.hardware_purchases enable row level security;
alter table public.hardware_purchase_items enable row level security;
alter table public.project_hardware_requirements enable row level security;
alter table public.project_production_stages enable row level security;
alter table public.project_sales enable row level security;
alter table public.project_receivables enable row level security;
alter table public.project_expenses enable row level security;

do $$ declare t text; begin foreach t in array array['hardware_suppliers','hardware_items','hardware_stock','hardware_purchases','hardware_purchase_items','project_hardware_requirements','project_production_stages','project_sales','project_receivables','project_expenses'] loop execute format('drop policy if exists %I_select_own on public.%I',t,t); execute format('drop policy if exists %I_insert_own on public.%I',t,t); execute format('drop policy if exists %I_update_own on public.%I',t,t); execute format('drop policy if exists %I_delete_own on public.%I',t,t); execute format('create policy %I_select_own on public.%I for select to authenticated using ((select auth.uid()) = user_id)',t,t); execute format('create policy %I_insert_own on public.%I for insert to authenticated with check ((select auth.uid()) = user_id)',t,t); execute format('create policy %I_update_own on public.%I for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id)',t,t); execute format('create policy %I_delete_own on public.%I for delete to authenticated using ((select auth.uid()) = user_id)',t,t); execute format('revoke all on public.%I from anon',t); execute format('grant select,insert,update,delete on public.%I to authenticated',t); end loop; end $$;