-- Client review / approval / contract / technical-drawing schema was applied directly
-- to Supabase production on 2026-09-10 with the migration:
-- client_review_approval_contract_and_technical_drawings
--
-- This repository marker intentionally contains no DDL so the migration reconcile
-- workflow will not attempt to recreate objects that already exist in production.
-- The authoritative production migration is recorded by Supabase migration history.
