-- Administrative access is role-based, never identity/UUID-based.
-- This migration intentionally does not grant a role to a hardcoded user.
-- Provisioning an administrator must create an explicit `admin` row in public.user_roles
-- through the trusted server-side provisioning path. Runtime authorization uses
-- public.is_admin_user(), which is hardened in the P1 migration.
