-- Applied to production on 2026-09-10 via Supabase migration tooling.
-- This file is the repository source-of-truth for the client review architecture.

create extension if not exists pgcrypto;

create table if not exists public.project_versions (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, version_number integer not null check (version_number > 0), status text not null default 'draft' check (status in ('draft','shared','approved','superseded')), snapshot jsonb not null default '{}'::jsonb, render_path text, technical_drawing_path text, cut_plan_path text, client_budget_summary jsonb, created_at timestamptz not null default now(), unique(project_id, version_number));
create index if not exists project_versions_project_idx on public.project_versions(project_id, version_number desc);

create table if not exists public.project_share_links (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, project_version_id uuid not null references public.project_versions(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, token_hash text not null unique, expires_at timestamptz not null, revoked_at timestamptz, require_verification boolean not null default false, created_at timestamptz not null default now(), last_accessed_at timestamptz);
create index if not exists project_share_links_project_idx on public.project_share_links(project_id);
create table if not exists public.project_share_access_logs (id uuid primary key default gen_random_uuid(), share_link_id uuid not null references public.project_share_links(id) on delete cascade, action text not null check (action in ('view','approve','request_change','contract_view','signature')), occurred_at timestamptz not null default now(), metadata jsonb not null default '{}'::jsonb);

create table if not exists public.client_change_requests (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, project_version_id uuid not null references public.project_versions(id) on delete restrict, share_link_id uuid not null references public.project_share_links(id) on delete restrict, status text not null default 'open' check (status in ('open','in_review','accepted','rejected','resolved')), requested_by_name text, requested_by_email text, summary text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.client_change_request_messages (id uuid primary key default gen_random_uuid(), change_request_id uuid not null references public.client_change_requests(id) on delete cascade, sender_type text not null check (sender_type in ('client','owner','iara')), message_type text not null check (message_type in ('text','audio','system')), body text, audio_path text, transcript text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), check (body is not null or audio_path is not null or message_type = 'system'));

create table if not exists public.project_approvals (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, project_version_id uuid not null references public.project_versions(id) on delete restrict, share_link_id uuid not null references public.project_share_links(id) on delete restrict, client_name text not null, client_email text, approved_at timestamptz not null default now(), evidence jsonb not null default '{}'::jsonb, document_hash text);
create unique index if not exists project_approvals_version_unique on public.project_approvals(project_version_id);

create table if not exists public.project_contracts (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, approved_version_id uuid references public.project_versions(id) on delete restrict, user_id uuid not null references auth.users(id) on delete cascade, contract_number text, status text not null default 'draft' check (status in ('draft','sent','signed','cancelled')), party_data jsonb not null default '{}'::jsonb, project_data jsonb not null default '{}'::jsonb, document_path text, document_hash text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.project_contract_signatures (id uuid primary key default gen_random_uuid(), contract_id uuid not null references public.project_contracts(id) on delete cascade, signer_type text not null check (signer_type in ('client','owner')), signer_name text not null, signer_email text, provider text, provider_request_id text, status text not null default 'pending' check (status in ('pending','sent','signed','declined','expired')), signed_at timestamptz, evidence jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());

alter table public.project_versions enable row level security; alter table public.project_share_links enable row level security; alter table public.project_share_access_logs enable row level security; alter table public.client_change_requests enable row level security; alter table public.client_change_request_messages enable row level security; alter table public.project_approvals enable row level security; alter table public.project_contracts enable row level security; alter table public.project_contract_signatures enable row level security;

create policy project_versions_owner_all on public.project_versions for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy project_share_links_owner_all on public.project_share_links for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy share_logs_owner_select on public.project_share_access_logs for select using (exists (select 1 from public.project_share_links s where s.id = share_link_id and s.user_id = auth.uid()));
create policy change_requests_owner_all on public.client_change_requests for all using (exists (select 1 from public.projects p where p.id = project_id and p.user_id = auth.uid())) with check (exists (select 1 from public.projects p where p.id = project_id and p.user_id = auth.uid()));
create policy change_messages_owner_select on public.client_change_request_messages for select using (exists (select 1 from public.client_change_requests r join public.projects p on p.id = r.project_id where r.id = change_request_id and p.user_id = auth.uid()));
create policy approvals_owner_select on public.project_approvals for select using (exists (select 1 from public.projects p where p.id = project_id and p.user_id = auth.uid()));
create policy contracts_owner_all on public.project_contracts for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy signatures_owner_all on public.project_contract_signatures for all using (exists (select 1 from public.project_contracts c where c.id = contract_id and c.user_id = auth.uid())) with check (exists (select 1 from public.project_contracts c where c.id = contract_id and c.user_id = auth.uid()));

revoke all on public.project_versions from anon, authenticated; revoke all on public.project_share_links from anon, authenticated; revoke all on public.project_share_access_logs from anon, authenticated; revoke all on public.client_change_requests from anon, authenticated; revoke all on public.client_change_request_messages from anon, authenticated; revoke all on public.project_approvals from anon, authenticated; revoke all on public.project_contracts from anon, authenticated; revoke all on public.project_contract_signatures from anon, authenticated;
grant select, insert, update, delete on public.project_versions to authenticated; grant select, insert, update, delete on public.project_share_links to authenticated; grant select on public.project_share_access_logs to authenticated; grant select, insert, update, delete on public.client_change_requests to authenticated; grant select, insert, update, delete on public.client_change_request_messages to authenticated; grant select on public.project_approvals to authenticated; grant select, insert, update, delete on public.project_contracts to authenticated; grant select, insert, update, delete on public.project_contract_signatures to authenticated;

create or replace function public.client_review_project(p_token text) returns jsonb language plpgsql security definer set search_path = '' as $$ declare v_share public.project_share_links; v_version public.project_versions; begin select * into v_share from public.project_share_links where token_hash=encode(extensions.digest(p_token,'sha256'),'hex') and revoked_at is null and expires_at>now() limit 1; if not found then return jsonb_build_object('ok',false,'error','link_invalid_or_expired'); end if; select * into v_version from public.project_versions where id=v_share.project_version_id; update public.project_share_links set last_accessed_at=now() where id=v_share.id; insert into public.project_share_access_logs(share_link_id,action) values(v_share.id,'view'); return jsonb_build_object('ok',true,'share_link_id',v_share.id,'project_id',v_share.project_id,'version_id',v_version.id,'version_number',v_version.version_number,'snapshot',v_version.snapshot,'render_path',v_version.render_path,'technical_drawing_path',v_version.technical_drawing_path,'cut_plan_path',v_version.cut_plan_path,'client_budget_summary',v_version.client_budget_summary); end $$;
grant execute on function public.client_review_project(text) to anon, authenticated;

create or replace function public.client_request_project_change(p_token text,p_client_name text,p_client_email text,p_summary text,p_message_type text,p_body text default null,p_audio_path text default null,p_transcript text default null) returns jsonb language plpgsql security definer set search_path = '' as $$ declare v_share public.project_share_links; v_req public.client_change_requests; begin select * into v_share from public.project_share_links where token_hash=encode(extensions.digest(p_token,'sha256'),'hex') and revoked_at is null and expires_at>now() limit 1; if not found then return jsonb_build_object('ok',false,'error','link_invalid_or_expired'); end if; if p_message_type not in ('text','audio') then return jsonb_build_object('ok',false,'error','invalid_message_type'); end if; insert into public.client_change_requests(project_id,project_version_id,share_link_id,requested_by_name,requested_by_email,summary) values(v_share.project_id,v_share.project_version_id,v_share.id,p_client_name,p_client_email,p_summary) returning * into v_req; insert into public.client_change_request_messages(change_request_id,sender_type,message_type,body,audio_path,transcript) values(v_req.id,'client',p_message_type,p_body,p_audio_path,p_transcript); insert into public.project_share_access_logs(share_link_id,action,metadata) values(v_share.id,'request_change',jsonb_build_object('change_request_id',v_req.id)); return jsonb_build_object('ok',true,'change_request_id',v_req.id); end $$;
grant execute on function public.client_request_project_change(text,text,text,text,text,text,text,text) to anon, authenticated;

create or replace function public.client_approve_project(p_token text,p_client_name text,p_client_email text,p_evidence jsonb default '{}'::jsonb) returns jsonb language plpgsql security definer set search_path = '' as $$ declare v_share public.project_share_links; v_version public.project_versions; v_approval public.project_approvals; begin select * into v_share from public.project_share_links where token_hash=encode(extensions.digest(p_token,'sha256'),'hex') and revoked_at is null and expires_at>now() limit 1; if not found then return jsonb_build_object('ok',false,'error','link_invalid_or_expired'); end if; select * into v_version from public.project_versions where id=v_share.project_version_id; if exists(select 1 from public.project_approvals where project_version_id=v_version.id) then return jsonb_build_object('ok',false,'error','version_already_approved'); end if; insert into public.project_approvals(project_id,project_version_id,share_link_id,client_name,client_email,evidence) values(v_share.project_id,v_version.id,v_share.id,p_client_name,p_client_email,p_evidence) returning * into v_approval; update public.project_versions set status='approved' where id=v_version.id; update public.projects set status='aprovado',aprovado_em=now() where id=v_share.project_id; insert into public.project_share_access_logs(share_link_id,action,metadata) values(v_share.id,'approve',jsonb_build_object('approval_id',v_approval.id)); return jsonb_build_object('ok',true,'approval_id',v_approval.id,'project_id',v_share.project_id,'version_id',v_version.id); end $$;
grant execute on function public.client_approve_project(text,text,text,jsonb) to anon, authenticated;

create or replace function public.create_project_version_and_share(p_project_id uuid,p_snapshot jsonb,p_render_path text,p_technical_drawing_path text,p_cut_plan_path text,p_client_budget_summary jsonb,p_token text,p_expires_at timestamptz) returns jsonb language plpgsql security definer set search_path = '' as $$ declare v_uid uuid:=auth.uid(); v_version public.project_versions; v_share public.project_share_links; v_next integer; begin if v_uid is null then raise exception 'authentication_required'; end if; if not exists(select 1 from public.projects where id=p_project_id and user_id=v_uid) then raise exception 'project_not_found'; end if; select coalesce(max(version_number),0)+1 into v_next from public.project_versions where project_id=p_project_id; insert into public.project_versions(project_id,user_id,version_number,status,snapshot,render_path,technical_drawing_path,cut_plan_path,client_budget_summary) values(p_project_id,v_uid,v_next,'shared',coalesce(p_snapshot,'{}'::jsonb),p_render_path,p_technical_drawing_path,p_cut_plan_path,p_client_budget_summary) returning * into v_version; insert into public.project_share_links(project_id,project_version_id,user_id,token_hash,expires_at) values(p_project_id,v_version.id,v_uid,encode(extensions.digest(p_token,'sha256'),'hex'),p_expires_at) returning * into v_share; return jsonb_build_object('ok',true,'version_id',v_version.id,'version_number',v_version.version_number,'share_link_id',v_share.id); end $$;
grant execute on function public.create_project_version_and_share(uuid,jsonb,text,text,text,jsonb,text,timestamptz) to authenticated;
