import { useEffect, useRef, useState } from 'react';
import { CreditCard, Sparkles, WalletCards, ArrowUpRight, Loader2, CheckCircle2, BookOpen, WifiOff, Trophy } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';

interface Plan { id: string; code: string; name: string; description: string | null; monthly_price_cents: number | null; status: string; features?: { ai_messages_monthly?: number | null; price_note?: string } | null; }
interface Product { id: string; code: string; name: string; description: string | null; operation_type: string; credit_type: string; credits: number; price_cents: number | null; status: string; }
interface Wallet { image_credits: number; contract_credits: number; cut_plan_credits: number; marcena_credits: number; }
const money=(cents:number|null)=>cents==null?'Preço a definir':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(cents/100);
const allowedProducts=new Set(['render_unit','contract_unit','cut_plan_unit']);
const allowedPlans=new Set(['essencial','profissional','empresa','pro_factory']);

const describeFunctionError = async (error: unknown) => {
  if (!error) return 'Não foi possível iniciar a compra.';
  const candidate = error as { message?: string; context?: Response };
  try {
    const response = candidate.context;
    if (response) {
      const payload = await response.clone().json().catch(() => null) as { error?: string } | null;
      if (payload?.error) return payload.error;
      if (response.status === 401) return 'Sua sessão expirou. Entre novamente para continuar.';
      if (response.status === 403) return 'A cobrança não foi autorizada para esta conta.';
      if (response.status >= 500) return 'O serviço de pagamento apresentou uma falha. Tente novamente em instantes.';
    }
  } catch { /* fall back to SDK message */ }
  return candidate.message || 'Não foi possível iniciar a compra.';
};

const invokeAsaas = async (body: Record<string, unknown>) => {
  const { data: { session } } = await supabase.auth.getSession();
  if (!session?.access_token) throw new Error('Sua sessão expirou. Entre novamente para continuar.');
  return supabase.functions.invoke('asaas', {
    body,
    headers: { Authorization: `Bearer ${session.access_token}` },
  });
};

export default function BillingPortal(){
  const [plans,setPlans]=useState<Plan[]>([]); const [products,setProducts]=useState<Product[]>([]); const [wallet,setWallet]=useState<Wallet|null>(null); const [loading,setLoading]=useState(true); const [buying,setBuying]=useState(''); const [message,setMessage]=useState(''); const autoPurchaseStarted=useRef(false);
  const load=async()=>{setLoading(true);try{const [{data:planRows,error:planError},{data:productRows,error:productError},{data:walletRow,error:walletError}]=await Promise.all([supabase.from('billing_plans').select('id,code,name,description,monthly_price_cents,status,features').eq('status','active').order('sort_order'),supabase.from('billing_credit_products').select('id,code,name,description,operation_type,credit_type,credits,price_cents,status').eq('status','active').order('sort_order'),supabase.from('billing_wallets').select('image_credits,contract_credits,cut_plan_credits,marcena_credits').maybeSingle()]);if(planError||productError||walletError)throw new Error('Não foi possível carregar a Central de Uso.');setPlans((planRows??[]) as Plan[]);setProducts((productRows??[]) as Product[]);setWallet((walletRow??null) as Wallet|null);setMessage('')}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível carregar a Central de Uso.')}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const customerFor=async()=>{const {data:authData,error:authError}=await supabase.auth.getUser();if(authError||!authData.user)throw new Error('Sua sessão expirou. Entre novamente para continuar.');const {data:linkedCustomer,error:lookupError}=await supabase.from('billing_customers').select('asaas_customer_id').eq('user_id',authData.user.id).order('created_at',{ascending:false}).limit(1).maybeSingle();if(lookupError)throw new Error('Não foi possível localizar o cadastro de cobrança.');if(linkedCustomer?.asaas_customer_id)return String(linkedCustomer.asaas_customer_id);const m=authData.user.user_metadata??{};const name=String(m.name??m.full_name??authData.user.email?.split('@')[0]??'Cliente Marcenapp').trim();const {data:created,error:createError}=await invokeAsaas({action:'create_customer',name,email:authData.user.email??undefined});if(createError)throw createError;const id=created?.customer?.id as string|undefined;if(!id)throw new Error('Não foi possível preparar o cliente no Asaas.');return id};
  const startPurchase=async(productKey:string)=>{if(!allowedProducts.has(productKey)||buying)return;setBuying(productKey);setMessage('Preparando sua compra…');try{const customerId=await customerFor();const {data,error}=await invokeAsaas({action:'create_product_payment',productKey,customerId,billingType:'UNDEFINED'});if(error)throw error;const url=data?.checkoutUrl??data?.payment?.invoiceUrl??data?.payment?.bankSlipUrl??data?.payment?.transactionReceiptUrl;if(!url)throw new Error('A cobrança foi criada, mas o Asaas não retornou um endereço de pagamento.');setMessage('Compra criada. Abrindo o pagamento seguro do Asaas…');window.location.href=String(url)}catch(e){setMessage(await describeFunctionError(e));setBuying('')}};
  const startPlan=async(plan:string)=>{if(!allowedPlans.has(plan)||buying)return;setBuying(plan);setMessage('Preparando sua assinatura…');try{const customerId=await customerFor();const {data,error}=await invokeAsaas({action:'create_subscription',plan,customerId,billingType:'UNDEFINED'});if(error)throw error;const url=data?.checkoutUrl??data?.subscription?.invoiceUrl??data?.subscription?.bankSlipUrl??data?.subscription?.transactionReceiptUrl;if(url){setMessage('Assinatura criada. Abrindo o pagamento seguro do Asaas…');window.location.href=String(url)}else{setMessage('Assinatura criada. A cobrança será acompanhada pelo Marcenapp.');setBuying('');await load()}}catch(e){setMessage(await describeFunctionError(e));setBuying('')}};
  useEffect(()=>{if(loading||autoPurchaseStarted.current)return;const purchase=new URLSearchParams(window.location.search).get('purchase');if(!purchase)return;if(allowedProducts.has(purchase)||allowedPlans.has(purchase)){autoPurchaseStarted.current=true;void(allowedProducts.has(purchase)?startPurchase(purchase):startPlan(purchase))}},[loading,products,plans]);
  if(loading)return <section className="rounded-2xl border bg-white p-6 shadow-sm">Carregando Central de Uso…</section>;
  return <section className="space-y-6">
    <div className="rounded-3xl bg-slate-900 p-6 text-white shadow-xl"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-widest text-indigo-300">Marcenapp</p><h2 className="mt-1 text-2xl font-black">Planos e Central de Uso</h2><p className="mt-2 max-w-2xl text-sm text-slate-300">O cadastro e as ferramentas básicas são gratuitos. Recursos que usam IA ou processamento pago consomem créditos; você pode comprar avulso ou usar a franquia do seu plano.</p></div><CreditCard className="hidden sm:block text-indigo-300" size={32}/></div></div>
    <div className="grid gap-4 md:grid-cols-3"><article className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><BookOpen size={18} className="text-emerald-700"/><h3 className="mt-3 font-black">Base gratuita</h3><p className="mt-2 text-sm leading-6 text-slate-600">Diário, registros de campo, texto, fotos e organização podem funcionar sem créditos.</p></article><article className="rounded-2xl border border-indigo-200 bg-indigo-50 p-5"><Sparkles size={18} className="text-indigo-700"/><h3 className="mt-3 font-black">IA por consumo</h3><p className="mt-2 text-sm leading-6 text-slate-600">Render, contrato, projeto assistido e outras operações inteligentes usam créditos.</p></article><article className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><Trophy size={18} className="text-amber-700"/><h3 className="mt-3 font-black">Progresso</h3><p className="mt-2 text-sm leading-6 text-slate-600">O uso da plataforma também alimenta o progresso e a gamificação do profissional.</p></article></div>
    {message&&<div role="status" aria-live="polite" className="flex items-start gap-3 rounded-2xl border border-indigo-100 bg-indigo-50 p-4 text-sm text-indigo-900"><CheckCircle2 size={18} className="mt-0.5 shrink-0 text-indigo-600"/><span>{message}</span></div>}
    <div className="grid gap-4 md:grid-cols-4">{[['Render',wallet?.image_credits??0],['Contratos',wallet?.contract_credits??0],['Plano de corte',wallet?.cut_plan_credits??0],['Marcenapp',wallet?.marcena_credits??0]].map(([label,value])=><div key={String(label)} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-2 text-slate-500"><WalletCards size={16}/><span className="text-xs font-bold uppercase tracking-wide">{label}</span></div><strong className="mt-2 block text-3xl text-slate-800">{value}</strong><p className="text-xs text-slate-400">créditos disponíveis</p></div>)}</div>
    <div className="rounded-3xl border bg-white p-6 shadow-sm"><div className="mb-5"><p className="text-xs font-black uppercase tracking-[.18em] text-primary">Planos mensais</p><h3 className="mt-1 text-2xl font-black text-slate-900">Assine se fizer sentido para o seu volume</h3><p className="mt-1 text-sm text-slate-500">Não é obrigatório. O plano existe para quem quer uma franquia mensal e mais previsibilidade.</p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{plans.map((plan,i)=><article key={plan.id} className={`rounded-2xl border p-5 ${i===1?'border-primary/40 bg-primary/[.03] shadow-lg shadow-primary/10':'border-slate-200'}`}><p className="text-xs font-black uppercase tracking-widest text-primary">{i===1?'Mais escolhido':'Plano mensal'}</p><h4 className="mt-1 text-xl font-black text-slate-900">{plan.name.replace('MARCENAPP ','')}</h4><p className="mt-4 text-3xl font-black">{money(plan.monthly_price_cents)}<span className="text-xs font-bold text-slate-500">/mês</span></p><p className="mt-3 min-h-12 text-sm leading-6 text-slate-600">{plan.description}</p>{plan.features?.ai_messages_monthly?<p className="mt-3 rounded-lg bg-primary/10 px-3 py-2 text-xs font-black text-primary">{plan.features.ai_messages_monthly.toLocaleString('pt-BR')} mensagens de IA/mês</p>:<p className="mt-3 rounded-lg bg-slate-100 px-3 py-2 text-xs font-black text-slate-600">Configuração personalizada</p>}<button type="button" disabled={Boolean(buying)} onClick={()=>void startPlan(plan.code)} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-black text-white disabled:opacity-60">{buying===plan.code?'Preparando…':'Escolher plano'}{buying===plan.code?<Loader2 size={15} className="animate-spin"/>:<ArrowUpRight size={15}/>}</button></article>)}</div></div>
    <div className="rounded-3xl border bg-white p-6 shadow-sm"><div className="mb-5"><p className="text-xs font-black uppercase tracking-[.18em] text-primary">Créditos avulsos</p><h3 className="mt-1 text-2xl font-black text-slate-900">Compre somente o recurso que precisar</h3><p className="mt-1 text-sm text-slate-500">Sem mensalidade. Um crédito para uma operação paga.</p></div><div className="grid gap-4 md:grid-cols-3">{products.filter(p=>allowedProducts.has(p.code)).map(product=><article key={product.id} className="rounded-2xl border border-slate-200 p-5"><p className="text-xs font-black uppercase tracking-widest text-primary">Compra única</p><h4 className="mt-1 text-xl font-black">{product.name}</h4><p className="mt-2 min-h-12 text-sm leading-6 text-slate-600">{product.description}</p><div className="mt-5 flex items-end justify-between gap-3"><div><p className="text-2xl font-black">{money(product.price_cents)}</p><p className="text-xs text-slate-500">{product.credits} crédito</p></div><button type="button" disabled={Boolean(buying)} onClick={()=>void startPurchase(product.code)} className="rounded-xl border border-primary/30 px-4 py-2.5 text-sm font-black text-primary disabled:opacity-60">{buying===product.code?'Preparando…':'Comprar'}</button></div></article>)}</div></div>
    <div className="rounded-2xl border border-indigo-100 bg-indigo-50 p-5 text-sm text-indigo-900"><strong>Pagamento seguro:</strong> o Marcenapp cria a cobrança no servidor, abre o pagamento do Asaas e usa o Webhook para confirmar a operação antes da liberação. <span className="ml-1 inline-flex items-center gap-1 font-semibold"><WifiOff size={13}/> O Diário não depende dessa cobrança.</span></div>
  </section>;
}
